--CREAR UNA ENTIDAD CON DDL
CREATE TABLE EMPLEADO(
ID_CLIENTE NUMBER, --ALMACENA DATOS DE TIPO NUMERICO
NOMBRE NVARCHAR2(100), --ES UNICO DE ORACLE Y SIRVE PARA ALMACENAR DATOS DE LONGITUD
APP NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100)
);

--DML
--INSERTAR VALORES EN LA TABLA
INSERT INTO EMPLEADO VALUES(1, 'ROBERTO', 'MORALES', 35, 'PROGRAMADOR JAVA', 'TI');
COMMIT; --UNA VEZ QUE SE EJECUTA UNA SENTENCIA  DML, DEBEMOS CONFIRMAR LOS CAMBIOS PARA TERMINAR CON LA TRANSACCION REALIZADA SI UNA TRANSACCION SE QUEDA SIN CONFIRMAR LA BASE DE DATOS QUEDARA BLOQUEADA POR EL USUARIO QUE REALIZO LA TRANSACION NINGUN OTRO USUARIO PODARA REALIZAR OPERACIONES DE PERSISTENCIA EN LA BASE DE DATOS

SELECT * FROM EMPLEADO;

--OPERACIONES PARA ELIMINAR
--EJECUTAR UN DDL PARA EJECUTAR LOS REGISTROS DE LA TABLA
DELETE FROM EMPLEADO;
--EJECUTAR UN DDL PARA ELIMINAR LA TABLA (DEJA DE EXISTIR EN LA BASE DE DATOS)
DROP TABLE EMPLEADO;

--USO DE LOS CONSTRAINTS 3 FORMAS DIFERENTES

--CREAR UNA ENTIDAD CON PRIMARY KEY --> PRIMERA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100)
);

--DDL CON PRIMARY KEY --> SEGUNDA FORMA

CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER ,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
PRIMARY KEY(ID_EMPLEADO)
);

--DDL CON PRIMARY KEY ---> TERCERA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER ,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);


//COMPLEMENTO//////////////////////////////////////////////
--AGREGAR INSERCIONES A LA TABLA DE EMPLEADO
INSERT INTO EMPLEADO VALUES(1, 'ROBERTO', 'MORALES', 35, 'PROGRAMADOR JAVA', 'TI');
INSERT INTO EMPLEADO VALUES(2,'SERGIO','COVARRUBIAS',25,'MANTENIMIENTO','SIS');
INSERT INTO EMPLEADO VALUES(3, 'JOSE', 'GARCIA', 25, 'PROGRAMADOR .NET', 'TI');
INSERT INTO EMPLEADO VALUES(4, 'CHENTE', 'VAZQUEZ', 42, 'INTENDENTE', 'LIMPIEZA');


COMMIT;

//MODIFICAR O CAMBIAR EL NOMBRE DE LA COLUMNA

ALTER TABLE EMPLEADO RENAME COLUMN APP TO APELLIDO;

SELECT * FROM EMPLEADO;

--DML PARA ACTUALIZAR
UPDATE EMPLEADO SET departamento = 'SISTEMAS' WHERE id_empleado = 4;

//FUNCION ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

//BUSQUEDA DE INFORMACION CON CARACTERES EN ESPECIFICO
--BUSCAR UN EMPLEADO QUE EMPIEZE CON LA LETRA A

SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'E%';

//BUSCAR UN EMPLEADO QUE SU NOMBRE CONTENGA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';

//BUSCAR UN EMPLEADO QUE SU NOMBRE FINALICE CON O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--USO DE LA TABLA DUAL : ES UNA TABLA ESPECIAL DE UNA SOLA FILA Y UNA SOLA COLUMNA LLAMADA DUMMY QUE SE CREA AUTOMATICAMENTE Y ESTA DISPONIBLE PARA TODOS LOS USUARIOS Y SE UTILIZA PARA EVALUAR EXPRESIONES LLAMAR FUNCIONES Y OBTENER EL VALOR DE  PSEUDOCLOMNAS COMO SYSDATE O USER
//Y ESTO NOS PROPORCIONA UN LUGAR PARA EJECUTAR SENTECIAS SELECT QUE NO REQUIEREN DATOS DE UNA TABLA REAL
SELECT 5+5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT LENGTH('ESTA ES UNA CADENA DE PRUEBA PAR EL USO DE LENGTH') AS TAMAÑO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR LOS EMPLEADO MAYORES DE 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;

--BUSCAR LOS EMPLEADO MENORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD < 30;

--BUSCAR EMPLEADOS MAYORES DE 24 Y MENORES DE 28
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 28 ;

--RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 28;

--BUSCAR LOS EMPLEADOS CON EL ID 1,3,4
SELECT * FROM EMPLEADO WHERE id_empleado = 1 OR id_empleado = 3 OR id_empleado = 4;

--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,3,4);

--FUNCION GROUP BY
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;

--USO DE LA FUNCION COUNT
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADO QUE TENGAS MAS DE 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADO FROM EMPLEADO WHERE EDAD > 25;

--FUNCION DE AGREGACION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE apellido LIKE '%A%';

--FUNCION DE AGREGACION MAX
SELECT MAX (EDAD) AS EDAD_MAX FROM EMPLEADO;

--FUNCION MIN
SELECT MIN (EDAD) AS EDAD_MIN FROM EMPLEADO;

--FUNCION AVG (AVERAGE)
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;

--FUNCION ROUND 
SELECT ROUND(AVG(EDAD), 0)AS PROMEDIO_EDAD FROM EMPLEADO;

--USO DE TO_CHAR CON FORMATO
--PUEDE CMABIAR EL FORMATO NUMERICO EJEMPLO AGREGAR VALORES $1,984,243.99
SELECT TO_CHAR(AVG(EDAD), 'fm99.0')AS PROMEDIO_EDAD FROM EMPLEADO WHERE EDAD < 32;

--DARLE UN FORMATO DIFERENTE
--FUNCION CONCAT
//SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO', '')

--USO DE PIPE O BARRA LATERAL --> ||
SELECT 'EL EMPLEADO'||NOMBRE||''||APELLIDO||' CON LA EDAD DE '||EDAD||' AÑOS TRABAJA EN EL DEPARTAMENTO DE '||DEPARTAMENTO||'COMO'||PUESTO AS DETALLE_EMPLEADO FROM EMPLEADO;

--SUBCONSULTA O CONSULTA ANIDADA
SELECT * FROM EMPLEADO WHERE
EDAD = (
SELECT MAX(EDAD) 
FROM EMPLEADO 
WHERE DEPARTAMENTO = ('SIS')
);

SELECT * FROM EMPLEADO WHERE
EDAD = (
SELECT MIN(EDAD) 
FROM EMPLEADO 
WHERE DEPARTAMENTO = ('SIS')
);






