
CREATE TABLE LIBRO(
ID_LIBRO NUMBER,
NOMBRE NVARCHAR2(100),
AUTOR NVARCHAR2(100),
GENERO NUMBER, -- 1.DRAMA 2.TERROR 3.CIENCIA FICCION 4.NOVELA 5.THRILLER
NO_PAGINAS NUMBER,
PRECIO NUMBER,
EDITORIAL NVARCHAR2(100),
CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)

);


INSERT INTO LIBRO VALUES(1, 'LOS JUEGOS DEL HAMBRE', 'SUZZANE COLLINS', 4, 500, 345, 'MOLINO');
INSERT INTO LIBRO VALUES(2, 'HARRY POTTER Y EL PRINCIPE MESTIZO', 'J.K ROWLIN', 0, 700, 0, 'SALAMNDRA');
INSERT INTO LIBRO VALUES(3,'MAZE RUNNER: CORRER O MORIR','JAMES DASHNER',1,400,299,'VR EDITORAS');
INSERT INTO LIBRO VALUES(4,'DIVERGENTE','VERONICA ROTH',1,487,320,'HARPER COLLINS');
INSERT INTO LIBRO VALUES(5,'It','Stephen King',2,1138,350,'Viking Press');
INSERT INTO LIBRO VALUES(6,'La chica del tren','Paula Hawkins',5,395,199.99,'Riverhead Books');
INSERT INTO LIBRO VALUES(7, 'El Nombre De La Rosa', 'Umberto Eco', 5, 512, 380, 'Bompiani');
INSERT INTO LIBRO VALUES(8, 'LA CASA DE LOS ESPÍRITUS', 'Isabel Allende', 1, 490, 330, 'Debolsillo');
INSERT INTO LIBRO VALUES(9, 'EL PSICOANALISTA', 'John Katzenbach', 5, 279,75, 'Ediciones B');
INSERT INTO LIBRO VALUES(10, 'CIEN AÑOS DE SOLEDAD', 'Gabriel García Márquez', 1, 259,90, 'Sudamericana');
COMMIT;
DELETE FROM LIBRO;

SELECT * FROM LIBRO;

--USO DE CASE USANDOLO COMO COMPLEMENTO
SELECT ID_LIBRO, NOMBRE, AUTOR, 
(CASE GENERO
      WHEN 1 THEN 'DRAMA'
      WHEN 2 THEN 'TERROR'
      WHEN 3 THEN 'CIENCIA FICCION'
      WHEN 4 THEN 'NOVELA'
      WHEN 5 THEN 'THRILLER'
      ELSE 'SIN GENERO'
      END
      ) AS GENERO , NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;
      
-----------------------------------------------------------------
SELECT ID_LIBRO, NOMBRE, AUTOR, GENERO,
(CASE
     WHEN NO_PAGINAS > 500 THEN 'ES LARGO TIENE ' ||NO_PAGINAS|| ' PAGINAS'
     WHEN NO_PAGINAS <= 500 THEN 'ES CORTO TIENE ' ||NO_PAGINAS|| ' PAGINAS'
     ELSE 'NO DE PAGINAS DESCONOCIDO'
     END
     ) AS NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;




