--PROCEDIMIENTOS ALMACENADOS (STORED PROCEDURED): ES UN BLOQUE PL/SQL QUE SE GUARDA EN LA BASE DE DATOS Y PUEDE SER EJECUTADO
--CUANDO SE NECESITE

--SIRVE PARA: 
        --AUTOMATIZAR TAREAS REPETITIVAS EN LUGAR DE ESCRIBIR LA MISMA CONSULTA O LOGICA SE GUARDA EN UN PROCEDIMIENTO Y SE EJECUTA CON UN SIMPLE EXEC
        --CENTRALIZAR LA LOGICA DE NEGOCIO MEJORAR EL RENDIMIENTO
        --REUTILIZACION
        --SEGURIDAD
        --MANTENIMIENTO FACIL
        
--POR QUE SE USA:
        --ESTANDARIZACION : TODAS LAS APLICACIONES LLAMAN AL PROCEDIMIENTO Y GARANTIZA EL CALCULO O ACCION CONSISTENTE
        --MENOS TRAFICO EN LA RED: EN VEZ DE MANDAR CONSULTAS LARGAS DESDE LA APLICACION SE MANDA SOLO A LLAMAR AL PROCEDIMIENTO
        --MODULARIDAD: EL SISTEMA QUEDA DIVIDIDO EN PIEZAS PEQUEÑAS (PROCEDIMIENTOS LO QUE FACILITA LA LECTURA Y EL MANTENIMIENTO)
        --CONTROL DE ERRORES: SE PUEDE MANEJAR EXCEPCIONES DIRECTAMENTE EN LA BASE DE DATOS.
        
        
--CREAR UN DDL 
CREATE TABLE CELULAR_PRD(
ID_CELULAR NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
CAPACIDAD NVARCHAR2(100),
COLOR NVARCHAR2(100),
PRECIO NVARCHAR2(100),
CONSTRAINT CEL_PRD_PK PRIMARY KEY(ID_CELULAR)
);

INSERT INTO CELULAR VALUES(1, 'SAMSUNG', 'SFE3', 'OCTA', '68GB', 'NEGRO', 9000);
INSERT INTO CELULAR VALUES(2, 'APPLE', 'IPHONE 13', 'HEXA', '128GB', 'BLANCO', 19000);
INSERT INTO CELULAR VALUES(3, 'XIAOMI', 'REDMI NOTE 11', 'OCTA', '64GB', 'AZUL', 6500);
INSERT INTO CELULAR VALUES(4, 'HUAWEI', 'P40 LITE', 'OCTA', '128GB', 'VERDE', 7800);
INSERT INTO CELULAR VALUES(5, 'MOTOROLA', 'MOTO G60', 'OCTA', '128GB', 'GRIS', 7200);
INSERT INTO CELULAR VALUES(6, 'SAMSUNG', 'GALAXY S21', 'OCTA', '256GB', 'PLATEADO', 15000);
INSERT INTO CELULAR VALUES(7, 'APPLE', 'IPHONE SE', 'QUAD', '64GB', 'ROJO', 10500);
INSERT INTO CELULAR VALUES(8, 'XIAOMI', 'POCO X3 PRO', 'OCTA', '128GB', 'NEGRO', 8200);
INSERT INTO CELULAR VALUES(9, 'HUAWEI', 'Y9 PRIME', 'OCTA', '64GB', 'AZUL', 5800);
INSERT INTO CELULAR VALUES(10, 'MOTOROLA', 'EDGE 20', 'OCTA', '256GB', 'BLANCO', 13500);

DELETE FROM CELULAR;

SELECT * FROM CELULAR;

--CREACION DEL PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_CELULAR
IS
--DECLARACION DE VARIABLES, CONSTANTES O CURSORES
BEGIN 
  --LIMPIAR MI TABLA QUE SERA MI RESPLADO DE INFORMACION
  DELETE FROM CELULAR_PRD;
  --REALIZAR EL RESPALDO DE CELULAR EN CELULAR_PRD
  INSERT INTO CELULAR_PRD(ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO)
  SELECT ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO FROM CELULAR;
  END;
  /
  
  --EJECUTAR O MANDAR A LLAMAR AL PROCEDIMIENTO PARA QUE REALLIZE LA ACCION O SENTENCIA QUE CONTIENE
  EXECUTE PR_RESPALDO_CELULAR;
  
  SELECT * FROM CELULAR;
  
  SELECT * FROM CELULAR_PRD;
  
  
  --REALIZAR UN PROCEDIMIENTO ALMACENADO PARA HACER EL 10% DE DESCUENTO EN TODOS LOS CELULARES
  CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO(P_DESCUENTO IN NUMBER)  --EJE 10 = 10%
  IS
  BEGIN
      UPDATE CELULAR
      SET PRECIO = PRECIO -(PRECIO *(P_DESCUENTO / 100));
      DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL ' ||P_DESCUENTO|| ' A TODOS LOS CELULARES');
      EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL APLICAR RL DESCUENTO ' || SQLERRM);
          
          END;
          /
          
          SELECT * FROM CELULAR;
          
          EXECUTE APLICAR_DESCUENTO(10);
          
          ROLLBACK; //ECHAR PARA ATRAS
          COMMIT; //CONFIRMACION
          