--FUNCIONES O FUNCTION : SON BLOQUES PL/SQL QUE RECIBE PARAMETROS DE ENTRADA(OPCIONALES) Y QUE EJECUTA UNA SERIE DE INSTRUCCIONESY DEVUELVE UN VALOR CON LA CLAUSULA RETURN
--SE USAN MUCHO CUANDO QUIERES REUTILIZAR CODIGO QUE SIEMPRE RETORNA UN RESULTADO (A DIFERENCIA DE UN PROCEDIMIENTO ALMACENADO QUE NO NECESAREAMENTE RETORNA UN VALOR)

--FUNCION QUE SUMA LOS NUMEROS
CREATE OR REPLACE FUNCTION SUMA(A NUMBER, B NUMBER)
RETURN NUMBER IS 
    RESULTADO NUMBER; --DECLARACION DE VARIABLES LOCALES
    BEGIN
    --LOGICA DE LA FUNCION
    RESULTADO := A + B;
    RETURN RESULTADO; --OBLIGATORIA POR QUE UNA FUNCION SIEMORE RETORNA UN VALOR
    
END;
/

--LLAMAR A LA FUNCION UNA VEZ COMPILADA
 SELECT SUMA(10,5) FROM DUAL;
 
 --INVOCACION MEDIANTE UN BLOQUE ANONIMO
 BEGIN DBMS_OUTPUT.PUT_LINE('EL RESULATADO DE LA SUMA ES: ' || SUMA(2, 6));
 END;
 /
 
 --EJERCICIOS A REALIZAR
 --CREAR UNA FUNCION QUE CALCULE EL AREA DE UN TRINAGULO
 CREATE OR REPLACE FUNCTION AREA_TRINAGULO(BASE NUMBER, ALTURA NUMBER)
RETURN NUMBER IS 
    RESULTADO NUMBER; --DECLARACION DE VARIABLES LOCALES
    BEGIN
    --LOGICA DE LA FUNCION
    RESULTADO := (BASE * ALTURA)/2;
    RETURN RESULTADO; --OBLIGATORIA POR QUE UNA FUNCION SIEMORE RETORNA UN VALOR
    
END;
/
 SELECT AREA_TRINAGULO(10,5) FROM DUAL;
 
 
 
 
 --FUNCION QUE RECIBA UN NUMERO Y DEVUELVA SI ES PAR O IMPAR
  CREATE OR REPLACE FUNCTION PAR_INPAR(NUMERO NUMBER)
  RETURN VARCHAR2 IS 
    RESULTADO VARCHAR2(10); --DECLARACION DE VARIABLES LOCALES
    BEGIN
    --LOGICA DE LA FUNCION
    IF MOD(NUMERO, 2) = 0 THEN
    RESULTADO := 'PAR';
    ELSE
    RESULTADO := 'IMPAR';
    END IF;
    RETURN RESULTADO; --OBLIGATORIA POR QUE UNA FUNCION SIEMORE RETORNA UN VALOR
END;
/
 BEGIN --INVOCAR CON UN BLOQUE ANONIMO
  DBMS_OUTPUT.PUT_LINE('El número 7 es: ' || PAR_INPAR(7));
  DBMS_OUTPUT.PUT_LINE('El número 8 es: ' || PAR_INPAR(8));
END;
 
 --CREAR UNA FUNCION QUE RECIBA UNA NOTA NUMERICA( A, B, C, F)Y RETORNE EL VALOR CORRESPONDIENTE
 
 
 CREATE OR REPLACE FUNCTION NOTA_LETRA(NOTA NUMBER)
RETURN VARCHAR2
IS
  V_RESULTADO VARCHAR2(2);
BEGIN
  IF NOTA >= 90 THEN
    V_RESULTADO := 'A';
  ELSIF NOTA >= 80 THEN
    V_RESULTADO := 'B';
  ELSIF NOTA >= 51 THEN
    V_RESULTADO := 'C';
  ELSE
    V_RESULTADO := 'F';
  END IF;

  RETURN V_RESULTADO;
END ;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('NOTA 95 = ' || NOTA_LETRA(95));
  DBMS_OUTPUT.PUT_LINE('NOTA 82 = ' || NOTA_LETRA(82));
  DBMS_OUTPUT.PUT_LINE('NOTA 75 = ' || NOTA_LETRA(75));
  DBMS_OUTPUT.PUT_LINE('NOTA 50 = ' || NOTA_LETRA(50));
END;
/
 
 
 --FUNCION QUE CALCULE LA EDAD A PARTIR DE LA FECHA DE NACIMIENTO
 
 CREATE OR REPLACE FUNCTION CALCULAR_EDAD(FECHA_NAC DATE)
RETURN NUMBER
IS
  V_EDAD NUMBER;
BEGIN
 
  V_EDAD := ROUND(MONTHS_BETWEEN(SYSDATE, FECHA_NAC) / 12);

  RETURN V_EDAD;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('EDAD DE NACIDO EL 28/04/2000 = ' || CALCULAR_EDAD(DATE '2000-04-28'));
  DBMS_OUTPUT.PUT_LINE('EDAD DE NACIDO EL 17/02/1998 = ' || CALCULAR_EDAD(DATE '1998-02-17'));
END;
/


 
 --FUNCION QUE CALCULE EL PRECIO FINAL DEPUES DE APLICAR UN DESCUENTO DEL 10%
 
 CREATE OR REPLACE FUNCTION PRECIO_FINAL(PRECIO NUMBER)
RETURN NUMBER
IS
  V_FINAL NUMBER;
BEGIN
  V_FINAL := PRECIO - (PRECIO * 0.10); 
  RETURN V_FINAL;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('PRECIO ORIGINAL: 100 - PRECIO FINAL: ' || PRECIO_FINAL(100));
  DBMS_OUTPUT.PUT_LINE('PRECIO ORIGINAL: 250 - PRECIO FINAL: ' || PRECIO_FINAL(250));
END;
/
 
 --CREAR UNA FUNCION QUE RECIBA NOMBRE Y APELLIDO Y DEVUELVA LAS INICIALES
 
 CREATE OR REPLACE FUNCTION DEVUELVE_INICIALES(NOMBRE IN VARCHAR2, APELLIDO IN VARCHAR2)
RETURN VARCHAR2
IS
    V_INICIALES VARCHAR2(10);
BEGIN
    
    V_INICIALES := SUBSTR(NOMBRE, 1, 1) || SUBSTR(APELLIDO, 1, 1);

    RETURN V_INICIALES;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('JORGE CONTRERAS → ' || DEVUELVE_INICIALES('JORGE', 'CONTRERAS'));
    DBMS_OUTPUT.PUT_LINE('CARLOS GARCIA → ' || DEVUELVE_INICIALES('CARLOS', 'GARCIA'));
END;
/


 --CREAR UNA FUNCION QUE RECIBA UN NUMERO DEL 1 AL 12 Y DEVUELVA EL NOMBRE DEL MES CORRESPONDIENTE
 
  CREATE OR REPLACE FUNCTION NUMERO_MES(NUMERO NUMBER)
RETURN VARCHAR2
IS
  V_RESULTADO VARCHAR2(20);
BEGIN
  IF NUMERO = 1 THEN
    V_RESULTADO := 'ENERO';
  ELSIF NUMERO = 2 THEN
    V_RESULTADO := 'FERBRERO';
  ELSIF NUMERO = 3 THEN
    V_RESULTADO := 'MARZO';
    ELSIF NUMERO = 4 THEN
    V_RESULTADO := 'ABRIL';
    ELSIF NUMERO = 5 THEN
    V_RESULTADO := 'MAYO';
    ELSIF NUMERO = 6 THEN
    V_RESULTADO := 'JUNIO';
    ELSIF NUMERO = 7 THEN
    V_RESULTADO := 'JULIO';
    ELSIF NUMERO = 8 THEN
    V_RESULTADO := 'AGOSTO';
    ELSIF NUMERO = 9 THEN
    V_RESULTADO := 'SEPTIEMBRE';
    ELSIF NUMERO = 10 THEN
    V_RESULTADO := 'OCTUBRE';
    ELSIF NUMERO = 11 THEN
    V_RESULTADO := 'NOVIEMBRE';
    ELSIF NUMERO = 12 THEN
    V_RESULTADO := 'DICIEMBRE';
  ELSE
    V_RESULTADO := 'MES DESCONOCIDO';
  END IF;

  RETURN V_RESULTADO;
END ;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('MES 1 = ' || NUMERO_MES(1));
  DBMS_OUTPUT.PUT_LINE('MES 4 = ' || NUMERO_MES(4));
  DBMS_OUTPUT.PUT_LINE('MWS 8 = ' || NUMERO_MES(8));
  DBMS_OUTPUT.PUT_LINE('MES 12 = ' || NUMERO_MES(12));
END;
/

 