--PAQUETE O PACKAGE ESTE ES UN CONTENERDOR LOGICO QUE AGRUPA PROCEDIMIENTOS, FUNCIONES, VARIABLES, CONSTANTES, TIPOS DE DATOS Y CURSORES
--TODO DENTRO DE UNA MISMA UNIDAD DE PROGRAMA
--> SE PARECE A UNA CARPETA DE CODIGO ORGANIZADA QUE PERMITE REUTILIZAR Y MANTENER MEJOR EL CODIGO

--UN PAQUETE TIENE DOS PARTES 
--1. ESPECIFICACION DEL PACKAGE(SPECIFICATION PACKAGE): 
        --ES LA INTERFAZ PUBLICA
        --DEFINE QUE PROCEDIMIENTOS FUNCIONES Y VARIABLES ESTAN DISPONOBLES PARA SER USADOS FUERA


--2.CUERPO DEL PACKAGE(PACKAGE BODY)
        --CONTIENE LA IMPLEMENTACION DE LO DECLARADO EN LA ESPECIFICAION
        --AQUI SE ESCRIBE LA LOGICA

CREATE OR REPLACE PACKAGE PKG_GENERAL IS
PROCEDURE PR_DETALLE_LIBRO;
FUNCTION SUMA(A NUMBER, B NUMBER) RETURN NUMBER;
END;
/

--PACKAGE BODY

CREATE OR REPLACE PACKAGE BODY PKG_GENERAL IS

PROCEDURE PR_DETALLE_LIBRO 
IS
  --PASO1. DECLARAR EL CURSOR
  CURSOR LIBRO_INFO IS
  SELECT NOMBRE,
  ( CASE GENERO
     WHEN 1 THEN 'DRAMA'
     WHEN 2 THEN 'TERROR'
     WHEN 3 THEN 'CIENCIA FICCION'
     WHEN 4 THEN 'NOVELA'
     WHEN 5 THEN 'THRILLER'
     ELSE 'SIN GENERO'
   END
     ) AS GENERO, PRECIO FROM LIBRO;
     
     --VARIABLES LOCALES
     LV_NOMBRE LIBRO.NOMBRE%TYPE; --SIRVE PARA GANTIZAR QUE ESTA VARIABLE QUE ESTOY ASIGNANDO ES PARA EL NOMBRE DEL LIBRO
     LV_GENERO NVARCHAR2(20);
     LV_PRECIO NUMBER;
     
     BEGIN
     --PASO 2 ABRIR EL CURSOR
     OPEN LIBRO_INFO;
     --PASO 3 RECUPERAR EL CURSOR
     LOOP
     --POR CADA FILA RECORRIDA SE TOMEN LOS DATOS DEL CURSOR
     FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
     --CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
     EXIT WHEN LIBRO_INFO%NOTFOUND; --NOT FOUND DEVUELVE UN TRUE SI EL ULTIMO FETCH NO OBTUVO FILA
     --MOSTRAR LOS DATOS DEL CURSOR
     DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO ' ||LV_NOMBRE|| ' ES DE GENERO ' ||LV_GENERO|| ' Y TIENE UN PRECIO DE '||LV_PRECIO);
     END LOOP;
     --PASO 4 CERRAR EL CURSOR
     CLOSE LIBRO_INFO;
     END;
     ---------------------
     FUNCTION SUMA(A NUMBER, B NUMBER)
RETURN NUMBER IS 
    RESULTADO NUMBER; --DECLARACION DE VARIABLES LOCALES
    BEGIN
    --LOGICA DE LA FUNCION
    RESULTADO := A + B;
    RETURN RESULTADO; --OBLIGATORIA POR QUE UNA FUNCION SIEMORE RETORNA UN VALOR
    
END; --CIERRA LA FUNCION
END;--CIERRA EL PACKAGE BODY
/

--PARA MANDARLO A LLAMAR
BEGIN
PKG_GENERAL.PR_DETALLE_LIBRO;
END;
/


BEGIN
DBMS_OUTPUT.PUT_LINE(PKG_GENERAL.SUMA(1,2));
END;
/