--CURSORES : ES UN MECANISMO QUE USA PL/SQL PARA RECORRER REGISTROS DE UNA CONSULTA SQL DE FORMA FILA POR FILA
--CUANDO EJECUTAMOS UN SELECT EN PL/SQL QUE DEVUELVE UNA SOLA FILA PUEDES USAR SELECT INTO
--PERO SI EL SELECT DEVUELVE VARIAS FILAS SE NECESITA UN CURSOR PARA RECORRELAS TODAS UNA A UNA

--CURSOR IMPLICITO: LOS DECLARA EL PROGRAMADOR SE USAN PARA RECORRER RESULTADOS DE UN SELECT QUE DEVUELVE VARIAS FILAS
--TIENE 4 PASOS : DECLARAR -> ABRIR -> RECUPERAR -> CERRAR

SELECT * FROM LIBRO;

CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
  --PASO1. DECLARAR EL CURSOR
  CURSOR LIBRO_INFO IS
  SELECT NOMBRE,
  ( CASE GENERO
     WHEN 1 THEN 'DRAMA'
     WHEN 2 THEN 'TERROR'
     WHEN 3 THEN 'CIENCIA FICCION'
     WHEN 4 THEN 'NOVELA'
     WHEN 5 THEN 'THRILLER'
     ELSE 'SIN GENERO'
   END
     ) AS GENERO, PRECIO FROM LIBRO;
     
     --VARIABLES LOCALES
     LV_NOMBRE LIBRO.NOMBRE%TYPE; --SIRVE PARA GANTIZAR QUE ESTA VARIABLE QUE ESTOY ASIGNANDO ES PARA EL NOMBRE DEL LIBRO
     LV_GENERO NVARCHAR2(20);
     LV_PRECIO NUMBER;
     
     BEGIN
     --PASO 2 ABRIR EL CURSOR
     OPEN LIBRO_INFO;
     --PASO 3 RECUPERAR EL CURSOR
     LOOP
     --POR CADA FILA RECORRIDA SE TOMEN LOS DATOS DEL CURSOR
     FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
     --CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
     EXIT WHEN LIBRO_INFO%NOTFOUND; --NOT FOUND DEVUELVE UN TRUE SI EL ULTIMO FETCH NO OBTUVO FILA
     --MOSTRAR LOS DATOS DEL CURSOR
     DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO ' ||LV_NOMBRE|| ' ES DE GENERO ' ||LV_GENERO|| ' Y TIENE UN PRECIO DE '||LV_PRECIO);
     END LOOP;
     --PASO 4 CERRAR EL CURSOR
     CLOSE LIBRO_INFO;
     END;
     /
     
     BEGIN
     PR_DETALLE_LIBRO;
     END;
     /
     
    

