--DDL : LENGUAJE DE DEFINICION Y MODIFICACION DE DATOS : CREATE, ALTER, DROP, UPDATE
--DML : LENGUAJE DE MANIPULACION DE DATOS : INSERT, SELECT, UPDATE Y DELETE
--DCL : LENGUAJE DE CONTROL DE DATOS : GRANT Y REVOKE

--MODIFICAR LA SESION ACTUAL PARA LA EJECUCION DE SCRITPS
ALTER SESSION SET  "_ORACLE_SCRIPT" = TRUE; --Ctrl + Enter : Es para ejecutar la linea.

--CREACION DEL USUARIO Y CONTRASEÑA
CREATE USER JORGECONTRERAS IDENTIFIED BY 280400;

--OTORGAR PRIVILEGIOS AL USUARIO

GRANT ALL PRIVILEGES TO JORGECONTRERAS;


