--DESACTIVAR LOS TRIGGERS
ALTER TRIGGER TR_I_CELULAR DISABLE;
ALTER TRIGGER TR_I_CELULAR ENABLE;

--TRIGGER A NIVEL FILA, PARA UNA AUDITORIA, MULTIPLE

CREATE OR REPLACE TRIGGER TR_MULTIPLE_CEL
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
FOR EACH ROW
DECLARE 
--RECUPERAR EL ID VALIDO(USANDO UN SEQUENCE)

--SECUENCIA O SEQUENCE : SE EMPLEA PARA GENERAR VALORES ENTEROS SECUENCIALES UNICOS Y ASIGNARSELOS A CAMPOS NUMERICOS
--GENERALMENTE SE USAN PARA LAS LLAVES PRIMARIAS ASEGURANDO QUE NO HAYA ID REPETIDOS
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(10);
LV_FECHA DATE;
BEGIN
SELECT S_ID_CEL.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA  FROM DUAL;

--REGISTRO EN LA BIT BITACORA

IF INSERTING THEN
   INSERT INTO BIT_CEL(ID_BIT,ID_CELULAR,MARCA,MODELO,PROCESADOR,CAPACIDAD,COLOR,PRECIO,MARCA_OLD,MODELO_OLD,PROCESADOR_OLD,CAPACIDAD_OLD,COLOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT,:NEW.ID_CELULAR,:NEW.MARCA,:NEW.MODELO,:NEW.PROCESADOR,:NEW.CAPACIDAD,:NEW.COLOR,:NEW.PRECIO,NULL,NULL,NULL,NULL,NULL,0,LV_USUARIO,LV_FECHA,'INSERT');
ELSIF UPDATING THEN
    INSERT INTO BIT_CEL (ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO,MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT,:NEW.ID_CELULAR,:NEW.MARCA,:NEW.MODELO,:NEW.PROCESADOR,:NEW.CAPACIDAD,:NEW.COLOR,:NEW.PRECIO,:OLD.MARCA,:OLD.MODELO,:OLD.PROCESADOR,:OLD.CAPACIDAD,:OLD.COLOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'UPDATE');
ELSIF DELETING THEN
    INSERT INTO BIT_CEL (ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO,MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO) 
    VALUES ( LV_ID_BIT, :OLD.ID_CELULAR,NULL,NULL,NULL,NULL,NULL,NULL,:OLD.MARCA,:OLD.MODELO,:OLD.PROCESADOR,:OLD.CAPACIDAD,:OLD.COLOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'DELETE');
END IF;

END;
/

INSERT INTO CELULAR VALUES(1, 'SAMSUNG', 'GALAXY 3', 'OCTACORE', '128GB', 'NEGRO', 34000);
INSERT INTO CELULAR VALUES(2, 'NOKIA', 'LUMIA', 'OCTACORE', '128GB', 'NEGRO', 5000);

DELETE FROM BIT_CEL;
DELETE FROM CELULAR;

SELECT * FROM CELULAR;
SELECT * FROM BIT_CEL;

--CREATE SEQUENCE S_ID_CEL
--START WITH 1
--MAXVALUE 999
--MINVALUE 1
--NOCYCLE;
--/