--TRIGGERS O DIPARADORES : ES UN BLOQUE DE CODIGO QUE SE EJECUTA AUTOMATICAMENTE EN RESPUESTA A CIERTOS EVENTOS EN UNA TABLA O VISTA
--INSERT UPDATE Y DELETE

--PARA QUE SE USAN LOS TRIGGERS : SIRVEN PARA REGISTRAR AUDITORIAS(BITACORAS DE CAMBIOS)
                                --VALIDAR REGLAS DE NEGOCIO COMPLEJAS
                                --MATENER INTEGRIDAD DE DATOS
                                --GENERAR VALORES AUTOMATICOS (POR EJEMPLO TIMESTAP O USUARIO QUE REALIZAO LA MODIFICACION)

--TIPOS DE TRIGGERS
        --BEFORE: ESTE SE EJECUTA ANTES DE QUE OCURRA LA OPERACION
        --AFTER: ESTE SE EJECUTA DESPUES DE QUE OCURRA LA OPERACION
        --INSTEAD OF : SE USA EN VISTAS REMPLAZA LA OPERACION DML
        
--NIVEL DEL TRIGGER
        --ROW : POR FILA : SE ACTIVA UNA VEZ POR CADA FILA AFECTADA
        --STATEMENT: POR SENTENCIA: SE ACTIVA UNA SOLA VEZ POR INSTRUCCION DE SQL SIN IMPORTAR CUANTAS FILAS AFECTE

--ESTRUCTURA DE UN TRIGGER

        --CREATE OR REPLACE TRIGGER  NOMBRE_TRIGGER
        --BEFORE|AFTER|INSTEAD OF) ---> INSERT OR UPDATE OR DELETE ON NOMBRE_TABLA
        --FOR EACH ROW <--- (si se usa por fila) 
        --DECLARE
        --BEGIN
        --END;
        --/

--VARIABLES ESPECIALES EN TRIGGER POR FILA (FOR EACH ROW)
            --OLD ---> REPRESENTA LOS VALORES ANTERIORES (ANTES DE MODIFICAR)
            --NEW ---> REPRESENTA LOS VALORES NUEVOS(DESPUES DE INSERTAR O MODIFICAR)
            --SOLO FUNCIONAN EN TRIGGER FOR EACH ROW

--TRIGGER PARA UNA AUDITORIA SIMPLE
--CREAR UNA ENTIDAD
CREATE TABLE CELULAR(
ID_CELULAR NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
CAPACIDAD NVARCHAR2(100),
COLOR NVARCHAR2(100),
PRECIO NUMBER,
CONSTRAINT CEL_PK PRIMARY KEY(ID_CELULAR)
);

--CREAR UNA ENTIDAD BITACORA QUE REGISTRARA CADA EVENTO OCURRIDO EN LA TABLA CELULAR

CREATE TABLE BIT_CEL(
ID_BIT NUMBER,

--VALORES NUEVOS :NEW
ID_CELULAR NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
CAPACIDAD NVARCHAR2(100),
COLOR NVARCHAR2(100),
PRECIO NUMBER,

--VALORES VIEJOS: OLD
MARCA_OLD NVARCHAR2(100),
MODELO_OLD NVARCHAR2(100),
PROCESADOR_OLD NVARCHAR2(100),
CAPACIDAD_OLD NVARCHAR2(100),
COLOR_OLD NVARCHAR2(100),
PRECIO_OLD NUMBER,

--CAMPOS DE CONTROL
USUARIO NVARCHAR2(100),
FECHA_MOV DATE,
MOVIMIENTO NVARCHAR2(100),
CONSTRAINT BIT_CEL_PK PRIMARY KEY(ID_BIT)
);

--TRIGGER
CREATE OR REPLACE TRIGGER TR_I_CELULAR
AFTER INSERT ON CELULAR
FOR EACH ROW 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
        --COMO RECUPERAR LA FECHA DEL SISTEMA
        SELECT SYSDATE INTO LV_FECHA FROM DUAL;
        
        --RECUPERAR EL USUARIO
        SELECT USER INTO LV_USUARIO FROM DUAL;
        
        --OBTENER UN ID VALIDO PARA MI TABLA BITACORA
        SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_CEL;
        
        INSERT INTO BIT_CEL(ID_BIT,ID_CELULAR,MARCA,MODELO,PROCESADOR,CAPACIDAD,COLOR,PRECIO,MARCA_OLD,MODELO_OLD,PROCESADOR_OLD,CAPACIDAD_OLD,COLOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT,:NEW.ID_CELULAR,:NEW.MARCA,:NEW.MODELO,:NEW.PROCESADOR,:NEW.CAPACIDAD,:NEW.COLOR,:NEW.PRECIO,NULL,NULL,NULL,NULL,NULL,0,LV_USUARIO,LV_FECHA,'INSERT');
        END TR_I_CELULAR;
/

--PRUEBAS
INSERT INTO CELULAR VALUES(1, 'SAMSUNG', 'GALAXY 3', 'OCTACORE', '128GB', 'NEGRO', 34000);
INSERT INTO CELULAR VALUES(2, 'NOKIA', 'LUMIA', 'OCTACORE', '128GB', 'NEGRO', 5000);

CREATE OR REPLACE TRIGGER TR_U_CELULAR
AFTER UPDATE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT   NUMBER;
    LV_USUARIO  NVARCHAR2(100);
    LV_FECHA    DATE;
BEGIN

    --COMO RECUPERAR LA FECHA DEL SISTEMA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    --RECUPERAR EL USUARIO
    SELECT USER INTO LV_USUARIO FROM DUAL;

    --OBTENER UN ID VALIDO PARA MI TABLA BITACORA
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_CEL;

    -- Insertar registro en bitácora con valores nuevos y viejos
    INSERT INTO BIT_CEL (ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO,MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT,:NEW.ID_CELULAR,:NEW.MARCA,:NEW.MODELO,:NEW.PROCESADOR,:NEW.CAPACIDAD,:NEW.COLOR,:NEW.PRECIO,:OLD.MARCA,:OLD.MODELO,:OLD.PROCESADOR,:OLD.CAPACIDAD,:OLD.COLOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'UPDATE');

END TR_U_CELULAR;
/


UPDATE CELULAR SET MARCA = 'APPLE' WHERE ID_CELULAR = 1;
UPDATE CELULAR SET MARCA = 'MOTOROLA' WHERE ID_CELULAR = 2;

CREATE OR REPLACE TRIGGER TR_D_CELULAR
AFTER DELETE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT   NUMBER;
    LV_USUARIO  NVARCHAR2(100);
    LV_FECHA    DATE;
BEGIN
    -- Recuperar la fecha del sistema
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    -- Recuperar el usuario
    SELECT USER INTO LV_USUARIO FROM DUAL;

    -- Obtener un ID válido para la bitácora
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_CEL;

    -- Insertar registro en bitácora con valores eliminados
    INSERT INTO BIT_CEL (ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO,MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO) 
    VALUES (
        LV_ID_BIT,
        :OLD.ID_CELULAR,    NULL,NULL,NULL,NULL,NULL,NULL,:OLD.MARCA,:OLD.MODELO,:OLD.PROCESADOR,:OLD.CAPACIDAD,:OLD.COLOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'DELETE');
END TR_D_CELULAR;
/

DELETE FROM CELULAR WHERE ID_CELULAR = 2;




SELECT * FROM CELULAR;

SELECT * FROM BIT_CEL;