--BLOQUES ANONIMOS : SE LES CONOCE ASI PORQUE NO TIENEN NOMBRE Y NO QUEDA GUARDADO EN LA BASE DE DATOS SOLO SE EJECUTA EN EL MOMENTO
--PARTES DE UN BLOQUE ANONIMO:
--DECLARACION ->OPCIONAL: VARIABLES CONSTANTES Y CURSORES.

--BLOQUE ANONIMO
--DECLARACION
DECLARE
    v_nombre NVARCHAR2(50) := 'JORGE';
--EJECUCION
BEGIN
    dbms_output.put_line('HOLA ' || v_nombre);
EXCEPTION
    WHEN zero_divide THEN
        dbms_output.put_line('NO SE PUEDE DIVIDIR');
END;
/ --INDICADOR HASTA AQUI SE VA A EJECUTAR MI BLOQUE

--USO DE CICLOS CON PL/SQL

DECLARE
LV_VARIABLE NUMBER := 0; --:= ES UNA ASIGNACION
BEGIN
    LOOP
       DBMS_OUTPUT.PUT_LINE('VALOR' || LV_VARIABLE);
       LV_VARIABLE := LV_VARIABLE + 1;
       --EXIT WHEN LV_VARIABLE = 10
        IF LV_VARIABLE = 10
           THEN EXIT;
        END IF;
        END LOOP;
END;
/

---> USO DE CICLO FOR Y LOOP
DECLARE
BEGIN
--FOR
FOR I IN 1..10
LOOP
    DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE FOR: ' || I);
    EXIT WHEN I = 6;
 END LOOP;
 END;
 /
 
 ---> USO DE WHILE Y LOOP
 
 DECLARE
 LV_ITERATOR NUMBER := 1;
 BEGIN
   WHILE LV_ITERATOR <= 6
   LOOP
      DBMS_OUTPUT.PUT_LINE('EL VALOR DEL ITERATOR CON WHILE ' || LV_ITERATOR);
      LV_ITERATOR := LV_ITERATOR + 1;
   END LOOP;
   
   END;
   /
   
   ---> USO DE LOOP Y VARIABLES BOOLEANAS
   DECLARE
          LV_VALIDADOR BOOLEAN := FALSE;
   BEGIN
       FOR I IN 1..20
       LOOP
          DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERADOR ' || I);
          IF I = 9 THEN
                   LV_VALIDADOR := TRUE;
          END IF;
          EXIT WHEN LV_VALIDADOR;
          END LOOP;
          END;
          /