--USO DE LA CLAUSULA JOIN: SE UTILIZA PARA COMBINAR FILAS DE 2 O MAS TABLAS, SEGUN LA COLUMNA RELACIONADA ENTRE ELLAS

--PADRE
CREATE TABLE PADRE(
ID_PADRE NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO NVARCHAR2(100),
EDAD NUMBER,
TRABAJO NVARCHAR2(100),
CONSTRAINT PADRE_PK PRIMARY KEY(ID_PADRE)
);

INSERT INTO PADRE VALUES(1, 'JUAN', 'HERNANDEZ', 45, 'INGENIERO CIVIL');
INSERT INTO PADRE VALUES(2, 'CARLOS', 'RAMIREZ', 50, 'PROFESOR');
INSERT INTO PADRE VALUES(3,'JOSE','BLANCO',25,'MECANICO');
INSERT INTO PADRE VALUES(4, 'PEDRO', 'PRIETO', 48, 'CARPINTERO');
INSERT INTO PADRE VALUES(5,'SERGIO','COVA',33,'MANTENIMIENTO');
COMMIT;

--HIJO
CREATE TABLE HIJO(
ID_HIJO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO NVARCHAR2(100),
EDAD NUMBER,
HOBBIE NVARCHAR2(100),
PADRE_ID NUMBER,
CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
CONSTRAINT PADRE_PK1 FOREIGN KEY(PADRE_ID) REFERENCES PADRE(ID_PADRE)
);

INSERT INTO HIJO VALUES(1, 'ALINE', 'MORALES', 27, 'VER TELEVISION', 1);
INSERT INTO HIJO VALUES(2, 'JAVIER', 'GOMEZ', 10, 'JUGAR FUTBOL', NULL);
INSERT INTO HIJO VALUES(3, 'MARIO', 'HERNANDEZ', 15, 'FUTBOL', 4);
INSERT INTO HIJO VALUES(4,'EDUARDO','BLANCO',25,'PROGRAMAR',5);
INSERT INTO HIJO VALUES(5, 'JARETH', 'CASTELLS', 24, 'JUGAR VIDEOJUEGOS', 2);
INSERT INTO HIJO VALUES(6,'PERLA','GARCIA',28,'NUTRIOLOGA',2);

SELECT * FROM HIJO;

--USO DEL INNER JOIN --> DEVUELVE LOS REGISTROS COINCIDENTES EN AMBAS TABLAS
SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DEL LEFT JOIN --> DEVUELVE TODOS LOS REGISTROS DE LA TABLA IZQUIERDA(HIJO) Y LOS VALORES COINCIDIENTES DE LA TABLA DERECHA (PADRE)
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;
--USO DEL LEFT JOIN QUITANDO COINCIDENCIAS
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--USO DE RIGHT JOIN --> DEVUELVE TODOS LOS REGISTROD DE LA TABLA DERECHA(PADRE) Y LOS VALORES COINCIDENTES DE LA TABLA IZQUIERDA(HIJO)
SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DE RIGHT JOIN SIN COINCIDENCIAS
SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--FULL JOIN --> DEVUELVE TODOS LOS REGISTROS DE AMBAS TABLAS Y SUS VALORES COINCIDENTES
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--FULL JOIN SIN COINCIDENCIAS
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;