--CREACION DE TABLAS
CREATE TABLE equipos (
    NOMBRE      VARCHAR2(20) PRIMARY KEY,
    CIUDAD      VARCHAR2(20),
    CONFERENCIA VARCHAR2(4),
    DIVISION    VARCHAR2(9)
);

CREATE TABLE jugadores (
    CODIGO       NUMBER PRIMARY KEY,
    NOMBRE       VARCHAR2(30),
    PROCEDENCIA  VARCHAR2(20),
    ALTURA       VARCHAR2(4),
    PESO         NUMBER,
    POSICION     VARCHAR2(5),
    NOMBRE_EQUIPO VARCHAR2(20),
    CONSTRAINT FK_JUGADORES_EQUIPO FOREIGN KEY (NOMBRE_EQUIPO)
        REFERENCES equipos(NOMBRE)
);

CREATE TABLE partidos (
    CODIGO           NUMBER PRIMARY KEY,
    EQUIPO_LOCAL     VARCHAR2(20),
    EQUIPO_VISITANTE VARCHAR2(20),
    PUNTOS_LOCAL     NUMBER,
    PUNTOS_VISITANTE NUMBER,
    TEMPORADA        VARCHAR2(5),
    CONSTRAINT FK_PARTIDOS_LOCAL FOREIGN KEY (EQUIPO_LOCAL)
        REFERENCES equipos(NOMBRE),
    CONSTRAINT FK_PARTIDOS_VISITANTE FOREIGN KEY (EQUIPO_VISITANTE)
        REFERENCES equipos(NOMBRE)
);

CREATE TABLE estadisticas (
    TEMPORADA           VARCHAR2(5),
    JUGADOR             NUMBER,
    PUNTOS_POR_PARTIDO  FLOAT(126),
    ASISTENCIAS_POR_PARTIDO FLOAT(126),
    TAPONES_POR_PARTIDO FLOAT(126),
    REBOTES_POR_PARTIDO FLOAT(126),
    CONSTRAINT ESTADISTICAS_PK PRIMARY KEY (TEMPORADA, JUGADOR),
    CONSTRAINT FK_ESTADISTICAS_JUGADOR FOREIGN KEY (JUGADOR)
        REFERENCES jugadores(CODIGO)
);



--1.	Mostrar el nombre de todos los jugadores ordenados alfabéticamente. (Debe devolver 432 registros.)
SELECT NOMBRE FROM JUGADORES
ORDER BY NOMBRE ASC;

--2.	Mostrar el nombre de todos los equipos ordenados alfabéticamente.
SELECT NOMBRE FROM EQUIPOS
ORDER BY NOMBRE ASC;

--3.	Mostrar el nombre de los equipos del este.
SELECT NOMBRE, CONFERENCIA FROM EQUIPOS
WHERE CONFERENCIA = 'East';

--4.	Mostrar los equipos donde su ciudad empieza por c.
SELECT NOMBRE, CIUDAD FROM EQUIPOS
WHERE CIUDAD LIKE 'C%';


--5.	Mostrar todos los jugadores y su equipo ordenado por nombre del equipo. (Debe devolver 432 registros)
SELECT NOMBRE, NOMBRE_EQUIPO FROM JUGADORES
ORDER BY NOMBRE_EQUIPO;

--6.	Mostrar todos los jugadores del equipo «Raptors».
SELECT NOMBRE, NOMBRE_EQUIPO FROM JUGADORES
WHERE NOMBRE_EQUIPO = 'Raptors';

--7.	Mostrar los puntos por partido de ‘Pau Gasol’.
SELECT J.NOMBRE, E.PUNTOS_POR_PARTIDO FROM ESTADISTICAS E 
INNER JOIN JUGADORES J ON E.JUGADOR = J.CODIGO
WHERE J.NOMBRE = 'Pau Gasol';


--8.	Mostrar los puntos por partido de ‘Pau Gasol’ en la temporada ’04/05′.
SELECT J.NOMBRE, E.PUNTOS_POR_PARTIDO, E.TEMPORADA FROM ESTADISTICAS E 
INNER JOIN JUGADORES J ON E.JUGADOR = J.CODIGO
WHERE J.NOMBRE = 'Pau Gasol' AND E.TEMPORADA = '04/05';


--9.	Mostrar el número de puntos de cada jugador en toda su carrera. (Debe devolver 424 registros.)
SELECT J.NOMBRE AS NOMBRE, 
SUM(E.PUNTOS_POR_PARTIDO) AS TOTAL_PUNTOS
FROM ESTADISTICAS E 
INNER JOIN JUGADORES J ON E.JUGADOR = J.CODIGO
GROUP BY J.NOMBRE
ORDER BY J.NOMBRE;

--10.	Mostrar el número de jugadores de cada equipo.
SELECT J.NOMBRE_EQUIPO,
       COUNT(*) AS NUMERO_JUGADORES
FROM JUGADORES J
GROUP BY J.NOMBRE_EQUIPO;


--11.	Mostrar el jugador que más puntos ha realizado en toda su carrera.
SELECT J.NOMBRE AS NOMBRE, 
SUM(E.PUNTOS_POR_PARTIDO) AS TOTAL_PUNTOS
FROM ESTADISTICAS E 
INNER JOIN JUGADORES J ON E.JUGADOR = J.CODIGO
GROUP BY J.NOMBRE
ORDER BY TOTAL_PUNTOS DESC
FETCH FIRST 1 ROWS ONLY;

--12.	Mostrar el nombre del equipo, conferencia y división del jugador más alto de la NBA.
SELECT E.NOMBRE,E.CONFERENCIA,E.DIVISION,J.NOMBRE,J.ALTURA
FROM JUGADORES J
INNER JOIN EQUIPOS E ON J.NOMBRE_EQUIPO = E.NOMBRE
ORDER BY J.ALTURA DESC
FETCH FIRST 1 ROWS ONLY;


--13.	Mostrar el partido o partidos (equipo_local, equipo_visitante y diferencia) con mayor diferencia de puntos. (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_PARTIDOS_MAYOR_DIFERENCIA  AS
SELECT P.EQUIPO_LOCAL, P.EQUIPO_VISITANTE,
       ABS(P.PUNTOS_LOCAL - P.PUNTOS_VISITANTE) AS DIFERENCIA
FROM PARTIDOS P
WHERE ABS(P.PUNTOS_LOCAL - P.PUNTOS_VISITANTE) = (
    SELECT MAX(ABS(P2.PUNTOS_LOCAL - P2.PUNTOS_VISITANTE))
    FROM PARTIDOS P2
);

SELECT * FROM V_PARTIDOS_MAYOR_DIFERENCIA;


--14.	Mostrar la media de puntos en partidos de los equipos de la división Pacific. (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_MEDIA_PUNTOS_PACIFIC AS
SELECT AVG(P.PUNTOS_LOCAL + P.PUNTOS_VISITANTE) AS MEDIA_PUNTOS
FROM PARTIDOS P
INNER JOIN EQUIPOS E1 ON P.EQUIPO_LOCAL = E1.NOMBRE
INNER JOIN EQUIPOS E2 ON P.EQUIPO_VISITANTE = E2.NOMBRE
WHERE E1.DIVISION = 'Pacific'
   OR E2.DIVISION = 'Pacific';
   
SELECT * FROM V_MEDIA_PUNTOS_PACIFIC;

--15.	Mostrar los puntos de cada equipo en los partidos, tanto de local como de visitante. Usa una vista (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_PUNTOS_EQUIPOS AS
SELECT P.CODIGO AS PARTIDO,
       P.EQUIPO_LOCAL AS EQUIPO_LOCAL,
       P.PUNTOS_LOCAL AS PUNTOS_LOCAL,
       P.EQUIPO_VISITANTE AS EQUIPO_VISITANTE,
       P.PUNTOS_VISITANTE AS PUNTOS_VISITANTE
FROM PARTIDOS P
ORDER BY PARTIDO ASC;

SELECT * FROM V_PUNTOS_EQUIPOS;

