--CREAR LA ENTIDAD MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO     NUMBER,
    NOMBRE             NVARCHAR2(200),
    CONCENTRACION      NVARCHAR2(100), 
    VIA_ADMINISTRACION NVARCHAR2(100), 
    LABORATORIO        NVARCHAR2(200),
    PRECIO             NUMBER,
    CONSTRAINT MED_PK PRIMARY KEY (ID_MEDICAMENTO)
);

--CREAR UNA ENTIDAD BITACORA QUE REGISTRARA CADA EVENTO OCURRIDO EN LA TABLA MEDICAMENTO

CREATE TABLE BIT_MED(

ID_BIT NUMBER,

--VALORES NUEVOS :NEW
    ID_MEDICAMENTO     NUMBER,
    NOMBRE             NVARCHAR2(200),
    CONCENTRACION      NVARCHAR2(100), 
    VIA_ADMINISTRACION NVARCHAR2(100), 
    LABORATORIO        NVARCHAR2(200),
    PRECIO             NUMBER,

--VALORES VIEJOS: OLD
    NOMBRE_OLD             NVARCHAR2(200),
    CONCENTRACION_OLD      NVARCHAR2(100), 
    VIA_ADMINISTRACION_OLD NVARCHAR2(100), 
    LABORATORIO_OLD        NVARCHAR2(200),
    PRECIO_OLD             NUMBER,

--CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_MED_PK PRIMARY KEY(ID_BIT)
);

--CREAR LA SECUENCIA
CREATE SEQUENCE S_ID_MED
START WITH 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;
/

--TRIGGER A NIVEL FILA, PARA UNA AUDITORIA, MULTIPLE

CREATE OR REPLACE TRIGGER TR_MULTIPLE_MED
AFTER INSERT OR UPDATE OR DELETE ON MEDICAMENTO
FOR EACH ROW
DECLARE 

--RECUPERAR EL ID VALIDO(USANDO UN SEQUENCE)
--SECUENCIA O SEQUENCE : SE EMPLEA PARA GENERAR VALORES ENTEROS SECUENCIALES UNICOS Y ASIGNARSELOS A CAMPOS NUMERICOS
--GENERALMENTE SE USAN PARA LAS LLAVES PRIMARIAS ASEGURANDO QUE NO HAYA ID REPETIDOS

LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(50);
LV_FECHA DATE;
BEGIN
SELECT S_ID_MED.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA  FROM DUAL;

--REGISTRO EN LA BIT BITACORA

IF INSERTING THEN
   INSERT INTO BIT_MED (ID_BIT, ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO,NOMBRE_OLD, CONCENTRACION_OLD, VIA_ADMINISTRACION_OLD, LABORATORIO_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
   VALUES (LV_ID_BIT, :NEW.ID_MEDICAMENTO, :NEW.NOMBRE, :NEW.CONCENTRACION, :NEW.VIA_ADMINISTRACION, :NEW.LABORATORIO, :NEW.PRECIO,NULL, NULL, NULL, NULL, 0,LV_USUARIO, LV_FECHA, 'INSERT');

ELSIF UPDATING THEN
   INSERT INTO BIT_MED (ID_BIT, ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO,NOMBRE_OLD, CONCENTRACION_OLD, VIA_ADMINISTRACION_OLD, LABORATORIO_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
   VALUES (LV_ID_BIT, :NEW.ID_MEDICAMENTO, :NEW.NOMBRE, :NEW.CONCENTRACION, :NEW.VIA_ADMINISTRACION, :NEW.LABORATORIO, :NEW.PRECIO,:OLD.NOMBRE, :OLD.CONCENTRACION, :OLD.VIA_ADMINISTRACION, :OLD.LABORATORIO, :OLD.PRECIO,LV_USUARIO, LV_FECHA, 'UPDATE');

ELSIF DELETING THEN
   INSERT INTO BIT_MED (ID_BIT, ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO,NOMBRE_OLD, CONCENTRACION_OLD, VIA_ADMINISTRACION_OLD, LABORATORIO_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
   VALUES (LV_ID_BIT, :OLD.ID_MEDICAMENTO, NULL, NULL, NULL, NULL, NULL,:OLD.NOMBRE, :OLD.CONCENTRACION, :OLD.VIA_ADMINISTRACION, :OLD.LABORATORIO, :OLD.PRECIO,LV_USUARIO, LV_FECHA, 'DELETE');
END IF;
END;
/


INSERT INTO MEDICAMENTO VALUES (1, 'Paracetamol', '500 mg', 'Oral', 'Genéricos S.A.', 50);
INSERT INTO MEDICAMENTO VALUES (2, 'Ibuprofeno', '400 mg', 'Oral', 'Farmacia del Pueblo', 75);
INSERT INTO MEDICAMENTO VALUES (3, 'Amoxicilina', '250 mg/5ml', 'Oral', 'Laboratorios Salud', 120);
COMMIT;


UPDATE MEDICAMENTO SET PRECIO = 5 WHERE ID_MEDICAMENTO = 1;
UPDATE MEDICAMENTO SET LABORATORIO = 'FARMACIA TEHUACAN' WHERE ID_MEDICAMENTO = 2;
UPDATE MEDICAMENTO SET CONCENTRACION = '500 mg/5ml' WHERE ID_MEDICAMENTO = 3;
COMMIT;


DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = 1;
DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = 2;
COMMIT;


SELECT * FROM BIT_MED;
SELECT * FROM MEDICAMENTO;

DELETE FROM MEDICAMENTO;
DELETE FROM BIT_MED;
COMMIT;



