--CREAR UNA TABLA PARA LA ENTIDAD PELICULA

CREATE TABLE PELICULA(
ID_PELICULA NUMBER,
TITULO NVARCHAR2(100),
DIRECTOR NVARCHAR2(100),
GENERO NVARCHAR2(100),
ANIO_ESTRENO NUMBER,
DURACION_MIN NUMBER,
RECAUDACION NUMBER,
CONSTRAINT PELICULAR_PK PRIMARY KEY(ID_PELICULA)
);

INSERT INTO PELICULA VALUES(1, 'The Matrix', 'Lana Wachowski, Lilly Wachowski', 'Ciencia Ficción', 1999, 136, 466000000);
INSERT INTO PELICULA VALUES(2, 'Inception', 'Christopher Nolan', 'Ciencia Ficción', 2010, 148, 829000000);
INSERT INTO PELICULA VALUES(3, 'TITANIC', 'JAMES CAMERON', 'ROMANCE', 1997, 195, 2200000000);
INSERT INTO PELICULA VALUES(4, 'AVATAR', 'JAMES CAMERON', 'CIENCIA FICCCION', 2009, 162,  280000000);
INSERT INTO PELICULA VALUES(5,'AVENGERS: ENDGAME','ANTHONY Y JOE RUSSO','SUPERHÉROES',2019,181,2797800564);
INSERT INTO PELICULA VALUES(6,'INTERSTELLAR','CHRISTOPHER NOLAN','CIENCIA FICCIÓN',2014,169,701729206);
INSERT INTO PELICULA VALUES(7,'Madagascar','Eric Darnell','COMEDIA',2005,85,532680671);
INSERT INTO PELICULA VALUES(8,'CARS','John Lasseter','COMEDIA',2006,117, 461983149);
INSERT INTO PELICULA VALUES(9, 'TOYSTORY', 'PIXAR', 'DIBUJOS ANIMADOS', 1995, 162,  30000000);

//EJERICICIOS A REALIZAR
//1 .- MOSTRAR LAS PELICULAR ORDENADAS POR RECAUDACION DE MAYOR A MENOR, APLICANDO UN FORMATO A LA MONEDA(EJE: $2,200,000,000.00)
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    TO_CHAR(RECAUDACION, '$999,999,999,999.00') AS RECAUDACION_FORMATO
FROM PELICULA
ORDER BY recaudacion DESC;

//2 .- CALCULAR EL PORMEDIO DE RACUDACIONDE LAS PELCIULAS ESTRENDAS DESPUES DEL 2002
SELECT 
    ROUND(AVG(RECAUDACION), 2) AS PROMEDIO_RECAUDACION
FROM PELICULA
WHERE ANIO_ESTRENO > 2002;

//3 .- MOSTRAR LAS PLELICULAS QUE DUREN MAS DE 150 MINUTOS Y CONVERTIR EL TITULO A MINUSCULAS
SELECT 
    LOWER(TITULO) AS TITULO_MINUSCULAS,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    RECAUDACION
FROM PELICULA
WHERE DURACION_MIN > 150;
//4 .- CONSULTAR LOS REGISTROS CUYO GENERO SEA CINCIENCIA FICCION Y ORDENAR POR ANIO DE ESTRENO DEL MAS ANTIGUO AL MAS RECIENTE
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    RECAUDACION
FROM PELICULA
WHERE UPPER(GENERO) LIKE 'CIENCIA FICCIÓN'
ORDER BY ANIO_ESTRENO ASC;
//5 .- MOSTRAR LAS PLELICULAS CUYA RECAUDACION ESTE ENTRE 500,000,000 Y 1,500,000,000.
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    RECAUDACION
FROM PELICULA
WHERE RECAUDACION BETWEEN 500000000 AND 1500000000;

//6 .- MOSTRAR LAS PELICULAS DE GENERO DE COMEDIA YA GREGAR AL FINAL DE LA RECAUDACION LA PALABRA 'PESOS'
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    TO_CHAR(RECAUDACION, '999,999,999,999') || ' PESOS' AS RECAUDACION_PESOS
FROM PELICULA
WHERE UPPER(GENERO) = 'COMEDIA';

//7 .- CONSTAR CUENTAS PLEICULAS HAY POR DIRECTOR
SELECT 
    UPPER(DIRECTOR)AS DIRECTOR,
    COUNT(*) AS TOTAL_PELICULAS
FROM PELICULA
GROUP BY UPPER(DIRECTOR);

//8 .- MPSTRAR LA PELICULAR CON MAYOR RECUDACION. AGREGAR EL FORMATO A MONEDA Y LA PALBRA PESOS AL FINAL DE LA CNATIDAD
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    ANIO_ESTRENO,
    DURACION_MIN,
    TO_CHAR(RECAUDACION, '$999,999,999,999.00') || ' PESOS' AS RECAUDACION_FORMATO
FROM PELICULA
WHERE RECAUDACION = (SELECT MAX(RECAUDACION) FROM PELICULA);

//9 .- MOSTRAR LA PELICULA MAS ANTINGUA(MENOR ANIO DE ESTRENO) Y ANTEPONER LAS PLABARAS"ESTRENADA EN : " EL ANIO
SELECT 
    TITULO,
    DIRECTOR,
    GENERO,
    DURACION_MIN,
    'ESTRENADA EN: ' || ANIO_ESTRENO AS ANIO_ESTRENO_FORMATO,
    RECAUDACION
FROM PELICULA
WHERE ANIO_ESTRENO = (SELECT MIN(ANIO_ESTRENO) FROM PELICULA);

//10. DESGLOSAR E;L DETALLE DE CADA PLEICULAREN UNA UNA SOLA COLUMNA(PIPES O CONCAT)
//EJEMPLO: LA PELICULA DE NOMBRE: RyF 7 FUE DIRIGIDA POR JUAN MARTINEZ EN NEL ANO 2009 TIENE UNA DURACION DE 200 MINUTOS ES DE GENERO ACCION Y TUVO
//UNA RECAUDACION EN PESOS DE $1, 399.887.00
SELECT 
    'LA PELICULA DE NOMBRE: ' || TITULO ||
    ' FUE DIRIGIDA POR ' || DIRECTOR ||
    ' EN EL AÑO ' || ANIO_ESTRENO ||
    ' TIENE UNA DURACION DE ' || DURACION_MIN || ' MINUTOS' ||
    ' ES DE GENERO ' || GENERO ||
    ' Y TUVO UNA RECAUDACION EN PESOS DE ' || TO_CHAR(RECAUDACION, '$999,999,999,999.00') AS DETALLE_COMPLETO
FROM PELICULA;






