DELETE FROM MEDICAMENTO;
DELETE FROM BIT_MED;

CREATE OR REPLACE TRIGGER TR_I_U_D_MEDICAMENTO
AFTER INSERT OR UPDATE OR DELETE ON MEDICAMENTO
--ES UN TRIGGER STATEMENT
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(50);
LV_FECHA DATE;
LV_MOV NVARCHAR2(20);

BEGIN
--RECUPERAR EL ID VALIDO
    SELECT S_ID_MED.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_MED(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END;
/

INSERT INTO MEDICAMENTO VALUES (1, 'Paracetamol', '500 mg', 'Oral', 'Genéricos S.A.', 50);
INSERT INTO MEDICAMENTO VALUES (2, 'Ibuprofeno', '400 mg', 'Oral', 'Farmacia del Pueblo', 75);
INSERT INTO MEDICAMENTO VALUES (3, 'Amoxicilina', '250 mg/5ml', 'Oral', 'Laboratorios Salud', 120);
COMMIT;


UPDATE MEDICAMENTO SET PRECIO = 5 WHERE ID_MEDICAMENTO = 1;
UPDATE MEDICAMENTO SET LABORATORIO = 'FARMACIA TEHUACAN' WHERE ID_MEDICAMENTO = 2;
UPDATE MEDICAMENTO SET CONCENTRACION = '500 mg/5ml' WHERE ID_MEDICAMENTO = 3;
COMMIT;


DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = 1;
DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = 2;
COMMIT;

SELECT * FROM MEDICAMENTO;
SELECT ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_MED;