-- EJERCICIOS 
-- CREAR UN CURSOR QUE RECORRA TODOS LOS EMPLEADOS Y MUESTRE SU NOMBRE, DEPARTAMENTO Y PUESTO

CREATE OR REPLACE PROCEDURE PR_DETALLE_EMPLEADO IS
  -- PASO 1. DECLARAR EL CURSOR
    CURSOR EMPLEADO_INFO IS
    SELECT
        NOMBRE,
        DEPARTAMENTO,
        PUESTO
    FROM
        EMPLEADO;
     
     -- VARIABLES LOCALES
    LV_NOMBRE       EMPLEADO.NOMBRE%TYPE; -- SIRVE PARA GARANTIZAR QUE ESTA VARIABLE QUE ESTOY ASIGNANDO ES PARA EL NOMBRE DEL EMPLEADO
    LV_DEPARTAMENTO NVARCHAR2(20);
    LV_PUESTO       NVARCHAR2(20);
BEGIN
     -- PASO 2 ABRIR EL CURSOR
    OPEN EMPLEADO_INFO;
     -- PASO 3 RECUPERAR EL CURSOR
    LOOP
     -- POR CADA FILA RECORRIDA SE TOMEN LOS DATOS DEL CURSOR
        FETCH EMPLEADO_INFO INTO
            LV_NOMBRE,
            LV_DEPARTAMENTO,
            LV_PUESTO;
     -- CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
        EXIT WHEN EMPLEADO_INFO%NOTFOUND; -- NOT FOUND DEVUELVE UN TRUE SI EL ULTIMO FETCH NO OBTUVO FILA
     -- MOSTRAR LOS DATOS DEL CURSOR
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL EMPLEADO '
                             || LV_NOMBRE
                             || ' ES DEL DEPARTAMENTO '
                             || LV_DEPARTAMENTO
                             || ' Y TIENE UN PUESTO DE '
                             || LV_PUESTO);

    END LOOP;
     -- PASO 4 CERRAR EL CURSOR
    CLOSE EMPLEADO_INFO;
END;
/

BEGIN
    PR_DETALLE_EMPLEADO;
END;
/
     
-- CREAR UN CURSOR QUE MUESTRE LOS ALUMNOS QUE EN SU CARRERA TENGA LA PALABRA INGENIERIA
CREATE OR REPLACE PROCEDURE PR_ALUMNOS_INGENIERIA IS
  -- PASO 1: DECLARAR EL CURSOR
    CURSOR ALUMNOS_ING IS
    SELECT
        ID_ALUMNO,
        NOMBRE,
        CARRERA,
        SEMESTRE
    FROM
        ALUMNO
    WHERE
        UPPER(CARRERA) LIKE '%ING%';

  -- VARIABLES LOCALES
    LV_ID_ALUMNO ALUMNO.ID_ALUMNO%TYPE;
    LV_NOMBRE    ALUMNO.NOMBRE%TYPE;
    LV_CARRERA   ALUMNO.CARRERA%TYPE;
    LV_SEMESTRE  ALUMNO.SEMESTRE%TYPE;
BEGIN
  -- PASO 2: ABRIR EL CURSOR
    OPEN ALUMNOS_ING;

  -- PASO 3: RECUPERAR LOS REGISTROS
    LOOP
        FETCH ALUMNOS_ING INTO
            LV_ID_ALUMNO,
            LV_NOMBRE,
            LV_CARRERA,
            LV_SEMESTRE;
        EXIT WHEN ALUMNOS_ING%NOTFOUND;  -- SALE CUANDO NO HAY MÁS REGISTROS

    -- MOSTRAR LOS DATOS DEL CURSOR
        DBMS_OUTPUT.PUT_LINE('ID: '
                             || LV_ID_ALUMNO
                             || ', NOMBRE: '
                             || LV_NOMBRE
                             || ', CARRERA: '
                             || LV_CARRERA
                             || ', SEMESTRE: '
                             || LV_SEMESTRE);

    END LOOP;

  -- PASO 4: CERRAR EL CURSOR
    CLOSE ALUMNOS_ING;
END;
/

BEGIN
    PR_ALUMNOS_INGENIERIA;
END;
/
     
-- CREAR UN CURSOR QUE RECIBA COMO PARAMETRO EL NOMBRE DEL DEPARTAMENTO Y RETORNE TODOS LOS EMPLEADOS DEL DEPARTAMENTO

CREATE OR REPLACE PROCEDURE PR_EMPLEADOS_POR_DEPARTAMENTO (
    P_DEPARTAMENTO IN NVARCHAR2
) IS
  -- PASO 1: DECLARAR EL CURSOR
    CURSOR EMPLEADOS_DEPT IS
    SELECT
        NOMBRE,
        DEPARTAMENTO,
        PUESTO
    FROM
        EMPLEADO
    WHERE
        DEPARTAMENTO = P_DEPARTAMENTO;

  -- VARIABLES LOCALES
    LV_NOMBRE       EMPLEADO.NOMBRE%TYPE;
    LV_DEPARTAMENTO EMPLEADO.DEPARTAMENTO%TYPE;
    LV_PUESTO       EMPLEADO.PUESTO%TYPE;
BEGIN
  -- PASO 2: ABRIR EL CURSOR
    OPEN EMPLEADOS_DEPT;

  -- PASO 3: RECUPERAR LOS REGISTROS
    LOOP
        FETCH EMPLEADOS_DEPT INTO
            LV_NOMBRE,
            LV_DEPARTAMENTO,
            LV_PUESTO;
        EXIT WHEN EMPLEADOS_DEPT%NOTFOUND;

    -- MOSTRAR LOS DATOS
        DBMS_OUTPUT.PUT_LINE('NOMBRE: '
                             || LV_NOMBRE
                             || ', DEPARTAMENTO: '
                             || LV_DEPARTAMENTO
                             || ', PUESTO: '
                             || LV_PUESTO);

    END LOOP;

  -- PASO 4: CERRAR EL CURSOR
    CLOSE EMPLEADOS_DEPT;
END;
/


BEGIN
    PR_EMPLEADOS_POR_DEPARTAMENTO('TI');
END;
/
