--CREAR UNA ENTIDAD PARA HACER EL RESPALDO DE LA TABLA MEDICAMENTO
CREATE TABLE MEDICAMENTO_PRD(
    ID_MEDICAMENTO     NUMBER,
    NOMBRE             NVARCHAR2(200),
    CONCENTRACION      NVARCHAR2(100), 
    VIA_ADMINISTRACION NVARCHAR2(100), 
    LABORATORIO        NVARCHAR2(200),
    PRECIO             NUMBER,
    CONSTRAINT MED_PK1 PRIMARY KEY (ID_MEDICAMENTO)
);

INSERT INTO MEDICAMENTO VALUES (1, 'Paracetamol', '500 mg', 'Oral', 'Genéricos S.A', 50);
INSERT INTO MEDICAMENTO VALUES (2, 'Ibuprofeno', '400 mg', 'Oral', 'Farmacia del Pueblo', 75);
INSERT INTO MEDICAMENTO VALUES (3, 'Amoxicilina', '250 mg/5ml', 'Oral', 'Laboratorios Salud', 120);
INSERT INTO MEDICAMENTO VALUES (4, 'CEFTRIAXONA', '250 mg/5ml', 'Oral', 'Laboratorios Salud', 120);
INSERT INTO MEDICAMENTO VALUES (5, 'LOSARTAN', '50 MG', 'ORAL', 'SALUD Y VIDA', 80);
INSERT INTO MEDICAMENTO VALUES (6, 'OMEPRAZOL', '20 MG', 'ORAL', 'FARMA PLUS', 110);
INSERT INTO MEDICAMENTO VALUES (7, 'DICLOFENACO', '75 MG', 'INYECCIÓN', 'GENÉRICOS S.A.', 65);

INSERT INTO MEDICAMENTO VALUES (8, 'CIPROFLOXACINO', '500 MG', 'ORAL', 'Laboratorios Tehuacan', 200);
INSERT INTO MEDICAMENTO VALUES (9, 'AZITROMICINA', '500 MG', 'ORAL', 'Laboratorios Tehuacan', 180);
INSERT INTO MEDICAMENTO VALUES (10, 'LOSARTÁN', '50 MG', 'ORAL', 'Laboratorios Tehuacan', 90);

INSERT INTO MEDICAMENTO VALUES (11, 'NAPROXENO', '500 MG', 'ORAL', 'Farmacia del Pueblo', 80);
INSERT INTO MEDICAMENTO VALUES (12, 'KETOROLACO', '10 MG', 'ORAL', 'Farmacia del Pueblo', 95);
INSERT INTO MEDICAMENTO VALUES (13, 'OMEPRAZOL', '20 MG', 'ORAL', 'Farmacia del Pueblo', 120);
INSERT INTO MEDICAMENTO VALUES (14, 'METFORMINA', '850 MG', 'ORAL', 'Farmacia del Pueblo', 60);
INSERT INTO MEDICAMENTO VALUES (15, 'ATORVASTATINA', '40 MG', 'ORAL', 'Farmacia del Pueblo', 150);
COMMIT;


DELETE FROM MEDICAMENTO;
COMMIT;

--CREACION DEL PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_MEDICAMENTO
IS
--DECLARACION DE VARIABLES, CONSTANTES O CURSORES
BEGIN 
  --LIMPIAR MI TABLA QUE SERA MI RESPLADO DE INFORMACION
  DELETE FROM MEDICAMENTO_PRD;
  --REALIZAR EL RESPALDO DE CELULAR EN CELULAR_PRD
  INSERT INTO MEDICAMENTO_PRD(ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO)
                       SELECT ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO FROM MEDICAMENTO;
  END;
  /
  
  --EJECUTAR O MANDAR A LLAMAR AL PROCEDIMIENTO PARA QUE REALLIZE LA ACCION O SENTENCIA QUE CONTIENE
  EXECUTE PR_RESPALDO_MEDICAMENTO;
  
  SELECT * FROM MEDICAMENTO;
  
  SELECT * FROM MEDICAMENTO_PRD;
  
  
  --CREAR LOS SIGUIENTES PROCEDIMIENTOS ALMACENADOS
  --1. REPLICAR EL DESCUENTO DEL 10% A TODOS LOS MEDICAMENTOS
  
  CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO_MEDICAMENTO
  IS
  BEGIN
      UPDATE MEDICAMENTO
      SET PRECIO = PRECIO -(PRECIO *(10 / 100));
      DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL 10% A TODOS LOS MEDICAMENTOS');
      EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL APLICAR RL DESCUENTO ' || SQLERRM);
          
          END;
          /
          
  SELECT * FROM MEDICAMENTO;
  EXECUTE APLICAR_DESCUENTO_MEDICAMENTO;
  ROLLBACK; //ECHAR PARA ATRAS
  
  
  --2. ELIMINAR UN MEDICAMENTO POR ID
  
    CREATE OR REPLACE PROCEDURE ELIMINAR_MEDICAMENTO(ID_MED IN NUMBER)
    IS
    BEGIN
      DELETE MEDICAMENTO
      WHERE ID_MEDICAMENTO = ID_MED;
      DBMS_OUTPUT.PUT_LINE('SE ELIMINO EL MEDICAMENTO');
      EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR MEDICAMENTO ' || SQLERRM);
          END;
          /
          
  SELECT * FROM MEDICAMENTO;
  EXECUTE ELIMINAR_MEDICAMENTO(15);
  ROLLBACK; //ECHAR PARA ATRAS
  
  --3. CREAR UN PROCEDIMIENTO QUE RECIBA COMO PARAMETRO EL NOMBRE DEL LABORATORIO Y RETORNE TODOS LOS MEDICAMENTOS ASOCIADOS A ESE LABORATORIO
  --REALIZAR LOS REGISTROS SUFICIENTES PARA VER QUE LAS PRUEBAS FUNCIONEN DE FORMA ADECUADA
  
  CREATE OR REPLACE PROCEDURE FILTRAR_MEDICAMENTOS (P_LABORATORIO IN VARCHAR2)
IS
BEGIN
FOR R IN (SELECT ID_MEDICAMENTO,
                     NOMBRE,
                     CONCENTRACION,
                     VIA_ADMINISTRACION,
                     LABORATORIO,
                     PRECIO
                FROM MEDICAMENTO
               WHERE LABORATORIO = P_LABORATORIO) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || R.ID_MEDICAMENTO ||
                             ' | Nombre: ' || R.NOMBRE ||
                             ' | Concentración: ' || R.CONCENTRACION ||
                             ' | Vía: ' || R.VIA_ADMINISTRACION ||
                             ' | Laboratorio: ' || R.LABORATORIO ||
                             ' | Precio: ' || R.PRECIO);
    END LOOP;

EXCEPTION
     WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No existen medicamentos para el laboratorio: ' || P_LABORATORIO);
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al obtener medicamentos: ' || SQLERRM);
END;
/

  SELECT * FROM MEDICAMENTO;
  EXECUTE FILTRAR_MEDICAMENTOS('Laboratorios Tehuacan');

