--EJERCICIOS SIMPLES
--1.LISTAR NOMBRE Y PRECIO DE TODOS LOS MEDICAMENTOS DE UN SOLO LABORATORIO(ELIJE EL QUE QUIERAS)
       
       CREATE OR REPLACE VIEW V_LAB_MED AS 
       SELECT NOMBRE, LABORATORIO, PRECIO
       FROM MEDICAMENTO ;
       
       SELECT * FROM V_LAB_MED WHERE LABORATORIO = 'Farmacia del Pueblo';
       
       
--2.MOSTRAR UNICAMENTE LOS MEDICAMENTOS CON PRECIO MAYOR A 50

CREATE OR REPLACE VIEW V_MED_PRECIO AS 
       SELECT ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO
       FROM MEDICAMENTO WHERE PRECIO > 50;
       
       SELECT * FROM V_MED_PRECIO;

--3.CALCULAR EL PRECIO PROMEDIO DE TODOS LOS MEDICAMENTO


CREATE OR REPLACE VIEW V_PROM_MED AS
SELECT 
    AVG(PRECIO) AS PRECIO_PROMEDIO
FROM 
    MEDICAMENTO;

                
SELECT * FROM V_PROM_MED;    


--4.MOSTRAR EL MEDICAMENTO MAS CARO Y MAS BARATO
CREATE OR REPLACE VIEW V_MEDICAMENTO_MIN_MAX AS
SELECT NOMBRE, PRECIO
FROM MEDICAMENTO
WHERE PRECIO = (SELECT MIN(PRECIO) FROM MEDICAMENTO)
   OR PRECIO = (SELECT MAX(PRECIO) FROM MEDICAMENTO);

SELECT * FROM V_MEDICAMENTO_MIN_MAX;

--5.UTILIZAR EL CASE PARA CLASIFICAR LOS MEDICAMENTOS 'ECONOMICO' 'MEDIO' 'CARO'


       CREATE OR REPLACE VIEW V_MED_CLASIF AS
       SELECT ID_MEDICAMENTO, NOMBRE, CONCENTRACION, VIA_ADMINISTRACION, LABORATORIO, PRECIO,
       CASE
          WHEN PRECIO <= 50 THEN ' PRECIO ECONOMICO'
          WHEN PRECIO BETWEEN 51 AND 150 THEN 'PRECIO MEDIO'
          ELSE 'PRECIO CARO'
          END AS CATEGORIA FROM MEDICAMENTO;
          
          SELECT * FROM V_MED_CLASIF;

--EJERCICIOS CON VISTAS COMPLEJAS
--CREAR UNA SEGUNDA TABLA LLAMADA VENTA ID ID_MED CANTIDAD Y FECHA Y REALIZAR LOS INSERT SUFIECIENTES PARA PRUEBAS


CREATE TABLE VENTAS(
          ID_VENTA NUMBER,
          MEDICAMENTO_ID NUMBER,
          CANTIDAD NUMBER,
          FECHA DATE,
          CONSTRAINT VENTAS_PK PRIMARY KEY(ID_VENTA),
          CONSTRAINT MED_FK FOREIGN KEY (MEDICAMENTO_ID)REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
          );

          INSERT INTO VENTAS VALUES(101, 1, 2, SYSDATE);
          INSERT INTO VENTAS VALUES(102, 2, 1, SYSDATE);
          INSERT INTO VENTAS VALUES(103, 1, 1, SYSDATE);
          INSERT INTO VENTAS VALUES(104, 3, 3, SYSDATE);
          INSERT INTO VENTAS VALUES(105, 1, 65, SYSDATE);
          INSERT INTO VENTAS VALUES(106, 2, 1, SYSDATE);
          INSERT INTO VENTAS VALUES(107, 1, 1, SYSDATE);
          INSERT INTO VENTAS VALUES(108, 3, 55, SYSDATE);
          INSERT INTO VENTAS VALUES(109, 1, 2, SYSDATE);
          INSERT INTO VENTAS VALUES(110, 2, 60, SYSDATE);
          INSERT INTO VENTAS VALUES(111, 1, 1, SYSDATE);
          INSERT INTO VENTAS VALUES(112, 3, 80, SYSDATE);
          INSERT INTO VENTAS VALUES(113, 5, 2, SYSDATE);
          INSERT INTO VENTAS VALUES(114, 1, 150, SYSDATE);
          INSERT INTO VENTAS VALUES(115, 3, 125, SYSDATE);
        COMMIT;
          
          DELETE FROM VENTAS;
          COMMIT;
          
          SELECT * FROM VENTAS;
    



--1.MOSTRAR EL TOTAL DE VENTAS POR MEDICAMENTO
 
          CREATE OR REPLACE VIEW V_VENTAS_TOTAL_MED AS
          SELECT M.NOMBRE, M.LABORATORIO, SUM(V.CANTIDAD) AS TOTAL_VENDIDO
          FROM MEDICAMENTO M
          LEFT JOIN VENTAS V ON M.ID_MEDICAMENTO = V.MEDICAMENTO_ID
          GROUP BY M.NOMBRE, M.LABORATORIO;
          
          SELECT * FROM V_VENTAS_TOTAL_MED;

--2.CALCULAR EL INGRESO TOTAL (CANTIDAD * PRECIO) GENERADO POR CADA MEDICAMENTO


CREATE OR REPLACE VIEW V_ING_TOTAL_MED AS
SELECT  M.ID_MEDICAMENTO, M.NOMBRE, SUM(V.CANTIDAD * M.PRECIO) AS INGRESO_TOTAL
FROM MEDICAMENTO M
LEFT JOIN VENTAS V ON  M.ID_MEDICAMENTO = V.MEDICAMENTO_ID
GROUP BY 
    M.ID_MEDICAMENTO, M.NOMBRE;

SELECT * FROM V_ING_TOTAL_MED;


--3.OBTENER EL MEDICAMENTO MAS VENDIDO


CREATE OR REPLACE VIEW V_MED_MAS_VEND AS
SELECT m.ID_MEDICAMENTO, m.NOMBRE, SUM(v.CANTIDAD) AS TOTAL_VENDIDO
FROM MEDICAMENTO m
INNER JOIN VENTAS v ON m.ID_MEDICAMENTO = v.MEDICAMENTO_ID
GROUP BY 
    m.ID_MEDICAMENTO, m.NOMBRE
ORDER BY 
TOTAL_VENDIDO DESC
FETCH FIRST 1 ROW ONLY;
    
    SELECT * FROM V_MED_MAS_VEND;


   
   
--4.MOSTRAR LOS MEDICAMENTOS QUE NO TENGAN VENTAS REALIZADAS

CREATE OR REPLACE VIEW V_MED_SIN_VENT AS

SELECT M.ID_MEDICAMENTO, M.NOMBRE, V.ID_VENTA
FROM MEDICAMENTO M
LEFT JOIN VENTAS V ON M.ID_MEDICAMENTO = V.MEDICAMENTO_ID
WHERE V.MEDICAMENTO_ID IS NULL
ORDER BY M.ID_MEDICAMENTO;

SELECT * FROM V_MED_SIN_VENT;


--5.MOSTRAR EL DETALLE CON EL NOMBRE DEL MEDICAMENTO LABORATORIO Y EL TOTAL VENDIDO CON UNCASE QUE INDIQUE 'POPULAR' 'MUY POPOLAR' 'NO PUPULAR'
CREATE OR REPLACE VIEW V_MED_POP AS
SELECT M.ID_MEDICAMENTO, M.NOMBRE, M.LABORATORIO, SUM(V.CANTIDAD) AS TOTAL_VENDIDO,
    CASE 
        WHEN SUM(V.CANTIDAD) >= 100 THEN 'MUY POPULAR'
        WHEN SUM(V.CANTIDAD) BETWEEN 50 AND 99 THEN 'POPULAR'
        ELSE 'NO POPULAR'
    END AS CLASIFICACION
FROM MEDICAMENTO M LEFT JOIN VENTAS V ON M.ID_MEDICAMENTO = V.MEDICAMENTO_ID
GROUP BY M.ID_MEDICAMENTO, M.NOMBRE, M.LABORATORIO
ORDER BY TOTAL_VENDIDO DESC;

SELECT * FROM V_MED_POP;

