--PRACTICA PARA USO DE CLAUSULA JOIN
--TABLA ALUMNO
CREATE TABLE ALUMNO(
ID_ALUMNO NUMBER,
NOMBRE NVARCHAR2(100),
CARRERA NVARCHAR2(100),
SEMESTRE NUMBER,
CONSTRAINT ALUMNO_PK PRIMARY KEY(ID_ALUMNO)
);

INSERT INTO ALUMNO VALUES (1, 'ANA PEREZ', 'ING. SISTEMAS', 3);
INSERT INTO ALUMNO VALUES (2, 'CARLOS HERRERA', 'DERECHO', 5);
INSERT INTO ALUMNO VALUES (3, 'FERNANDA GARCIA', 'ARQUITECTURA', 1);
INSERT INTO ALUMNO VALUES (4, 'JUAN GOMEZ', 'ING CIVIL', 7);
INSERT INTO ALUMNO VALUES (5, 'SOFIA RAMIREZ', 'PSICOLOGIA', 2);
COMMIT;

--TABLA MATERIA
CREATE TABLE MATERIA(
ID_MATERIA NUMBER,
NOMBRE NVARCHAR2(100),
CREDITOS NUMBER,
CONSTRAINT MATERIA_PK PRIMARY KEY(ID_MATERIA)
);

INSERT INTO MATERIA VALUES (101, 'BASES DE DATOS', 8);
INSERT INTO MATERIA VALUES (102, 'DERECHO MERCANTIL', 6);
INSERT INTO MATERIA VALUES (103, 'DISENO ARQUITECTONICO', 10);
INSERT INTO MATERIA VALUES (104, 'RESISTENCIA DE MATERIALES', 8);
INSERT INTO MATERIA VALUES (105, 'PSICOLOGIA GENERAL', 7);
INSERT INTO MATERIA VALUES (106, 'PROGRAMACION ORIENTADA A OBJETOS', 9);
COMMIT;

--TABLA INSCRIPCION
CREATE TABLE INSCRIPCION(
ID_INSCRIPCION NUMBER,
ALUMNO_ID NUMBER,
MATERIA_ID NUMBER,
CALIFICACION NUMBER,
CONSTRAINT INS_PK PRIMARY KEY(ID_INSCRIPCION),
CONSTRAINT ALU_FK FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ID_ALUMNO),
CONSTRAINT MATE_FK FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA(ID_MATERIA)
);

INSERT INTO INSCRIPCION VALUES (1, 1, 101, 95);
INSERT INTO INSCRIPCION VALUES (2, 1, 106, 88);
INSERT INTO INSCRIPCION VALUES (3, 2, 102, 75);
INSERT INTO INSCRIPCION VALUES (4, 3, 103, 80);
INSERT INTO INSCRIPCION VALUES (5, 4, 104, 70);
COMMIT;

--EJERCICIOS
--1.MUESTRA EL NOMBRE DEL ALUMNO SU MATERIA INSCRITA Y LA CALIFICACION DE TODOS LOS ALUMNOS QUE TENGAN MATERIAS INSCRITAS //INNER JOIN
SELECT 
    a.NOMBRE ALUMNO,
    m.NOMBRE MATERIA,
    i.CALIFICACION
FROM 
    ALUMNO a
INNER JOIN 
    INSCRIPCION i ON a.ID_ALUMNO = i.ALUMNO_ID
INNER JOIN 
    MATERIA m ON i.MATERIA_ID = m.ID_MATERIA;
    
--2.MOSTRAR TODOS LOS ALUMNOS CON SUS MATERIAS (SI EXISTEN) SI UN ALUMNO NO TIENE MATERIA DEBERA SALIR SIN MATERIA //LEFT JOIN
SELECT 
    a.NOMBRE  ALUMNO,
    m.NOMBRE  MATERIA
FROM 
    ALUMNO a
LEFT JOIN 
    INSCRIPCION i ON a.ID_ALUMNO = i.ALUMNO_ID
LEFT JOIN 
    MATERIA m ON i.MATERIA_ID = m.ID_MATERIA;

--3.MUESTRA UNICAMENTE ALUMNOS QUE NO TENGAN MATERIA CURSANDO //LEFT JOIN
SELECT 
    a.NOMBRE  ALUMNO,
    m.NOMBRE  MATERIA
FROM 
    ALUMNO a
LEFT JOIN 
    INSCRIPCION i ON a.ID_ALUMNO = i.ALUMNO_ID
LEFT JOIN 
    MATERIA m ON i.MATERIA_ID = m.ID_MATERIA
    WHERE m.id_materia IS NULL;
    
--4.MOSTRAR TODAS LAS MATERIAS CON LOS ALUMNOS INSCRITOS. SI ALGUNA MATERIA NO HA SIDO INSCRITA DEBERA DECIR SIN ALUMNOS //LEFT JOIN
SELECT 
    m.NOMBRE  MATERIA,
    a.NOMBRE  ALUMNO
FROM 
    MATERIA m
LEFT JOIN 
    INSCRIPCION i ON m.ID_MATERIA = i.MATERIA_ID
LEFT JOIN 
    ALUMNO a ON i.ALUMNO_ID = a.ID_ALUMNO;

--5.MOSTRAR TODAS LAS MATERIAS SIN ALUMNO //LEFT JOIN
SELECT 
    m.NOMBRE  MATERIA
FROM 
    MATERIA m
LEFT JOIN 
    INSCRIPCION i ON m.ID_MATERIA = i.MATERIA_ID
WHERE 
    i.ID_INSCRIPCION IS NULL;


--6.MOSTRAR TODOS LOS ALUMNOS Y TODAS LAS MATERIAS AUNQUE NO TENGAN COINCIDENCIAS //FULL JOIN
SELECT
    a.NOMBRE  ALUMNO,
    m.NOMBRE  MATERIA
FROM
    ALUMNO a
FULL JOIN INSCRIPCION i ON a.ID_ALUMNO = i.ALUMNO_ID
FULL JOIN MATERIA m ON i.MATERIA_ID = m.ID_MATERIA;

--7.MOSTRAR MATERIA Y ALUMNOS QUE NO TENGAN COINCIDENCIA //FULL JOIN
SELECT 
    a.NOMBRE ALUMNO,
    m.NOMBRE MATERIA
FROM 
    ALUMNO a
FULL JOIN INSCRIPCION i ON a.ID_ALUMNO = i.ALUMNO_ID
FULL JOIN MATERIA m ON i.MATERIA_ID = m.ID_MATERIA
WHERE 
    a.ID_ALUMNO IS NULL OR m.ID_MATERIA IS NULL;



