--PRACTICA PARA USO DE SENTENCIAS CASE Y CLAUSULAS JOIN
CREATE TABLE CINE(
ID_CINE NUMBER,
NOMBRE NVARCHAR2(100),
CIUDAD NVARCHAR2(100),
SALAS NUMBER,
TIPO NUMBER, --1.TRADICIONAL 2.VIP 3.IMAX
CONSTRAINT CINE_PK PRIMARY KEY(ID_CINE)
);

INSERT INTO CINE VALUES (1, 'CINEMEX CENTRO', 'CDMX', 8, 1);
INSERT INTO CINE VALUES (2, 'CINEPOLIS PALZA', 'MONTERREY', 12, 2);
INSERT INTO CINE VALUES (3, 'CINEMA LUX', 'GUADALAJARA', 6, 1);
INSERT INTO CINE VALUES (4, 'CINEPOLIS VIP ZONA RIO', 'TIJUANA', 10, 2);
INSERT INTO CINE VALUES (5, 'IMAX MEGA SCREEN', 'PUEBLA', 4, 3);
INSERT INTO CINE VALUES (6, 'CINEMAGIC', 'PUEBLA', 0, 0);
COMMIT;

--TABLE FUNCION
CREATE TABLE FUNCION(
ID_FUNCION NUMBER,
PELICULA NVARCHAR2(100),
DURACION NUMBER,
HORARIO NVARCHAR2(100),
CINE_ID NUMBER,
CLASIFICACION NUMBER, --1.A 2.B 3.C 4.PG13 5.R
CONSTRAINT FUNCION_PK PRIMARY KEY(ID_FUNCION),
CONSTRAINT CINE_FK FOREIGN KEY (CINE_ID) REFERENCES CINE(ID_CINE)
);

INSERT INTO FUNCION VALUES (1, 'AVENGER ENDGAME', 180, '18:00', 1, 5);
INSERT INTO FUNCION VALUES (2, 'FROZEN 2', 120, '16:00', 2, 1);
INSERT INTO FUNCION VALUES (3, 'BATMAN', 150, '20:00', 2, 5);
INSERT INTO FUNCION VALUES (4, 'SPIDERMAN', 140, '19:30', 3, 4);
INSERT INTO FUNCION VALUES(5, 'TOY STORY 4', 110, '15:00', 4, 1);
INSERT INTO FUNCION VALUES(6, 'JOKER', 122, '21:00', 5, 5);
INSERT INTO FUNCION VALUES(7, 'AVATAR 2', 190, '22:00', 5, 4);
INSERT INTO FUNCION VALUES(8, 'COCO', 105, '14:00', 1, 1);
INSERT INTO FUNCION VALUES(9, 'TITANIC', 195, '17:00', 3, 3);
INSERT INTO FUNCION VALUES(10, 'GUARDIANES DE LA GALAXIA', 130, '20:30', 4, 4);
COMMIT;

--CONSULTAS A REALIZAR 
--1. MOSTRAR TODAS LAS FUNCIONES CON EL NOMBRE DEL CINE Y USAR CASE PARA MOSTRAR EL TIPO DE CINE Y LA CLASIFICACION EN TEXTO //INNER JOIN
SELECT 
    f.ID_FUNCION,
    f.PELICULA,
    f.DURACION,
    f.HORARIO,
    c.NOMBRE AS CINE,
    c.CIUDAD,
    CASE c.TIPO
        WHEN 1 THEN 'TRADICIONAL'
        WHEN 2 THEN 'VIP'
        WHEN 3 THEN 'IMAX'
        ELSE 'DESCONOCIDO'
    END AS TIPO_CINE,
    CASE f.CLASIFICACION
        WHEN 1 THEN 'A'
        WHEN 2 THEN 'B'
        WHEN 3 THEN 'C'
        WHEN 4 THEN 'PG13'
        WHEN 5 THEN 'R'
        ELSE 'SIN CLASIFICAR'
    END AS CLASIFICACION
FROM FUNCION f
INNER JOIN CINE c ON f.CINE_ID = c.ID_CINE;

--2.CONTAR CUANTAS FUNCIONES HAY POR CINE //LEFT JOIN
SELECT 
    c.NOMBRE AS CINE,
    COUNT(f.ID_FUNCION) AS TOTAL_FUNCIONES
FROM CINE c
LEFT JOIN FUNCION f ON c.ID_CINE = f.CINE_ID
GROUP BY c.NOMBRE
ORDER BY TOTAL_FUNCIONES DESC;

--3.MOSTRAR EL CINE QUE TIENE MAS FUNCIONES PROGRAMADAS //INNER JOIN
SELECT 
    c.NOMBRE AS CINE,
    COUNT(f.ID_FUNCION) AS total_funciones
FROM 
    CINE c
INNER JOIN 
    FUNCION f ON c.ID_CINE = f.CINE_ID
GROUP BY 
    c.NOMBRE
ORDER BY 
    total_funciones DESC;


--4.MOSTRAR CUANTAS FUNCIONES HAY POR CADA CINE //RIGHT JOIN
SELECT 
    c.NOMBRE AS CINE,
    COUNT(f.ID_FUNCION) AS TOTAL_FUNCIONES
FROM FUNCION f
RIGHT JOIN CINE c ON f.CINE_ID = c.ID_CINE
GROUP BY c.NOMBRE;

--5.ORDENAR LAS FUNCIONES POR PELUCULA Y LUEGO POR DURACION ES UNA SOLA CONSULTA //INNER JOIN
SELECT 
    f.ID_FUNCION,
    f.PELICULA,
    f.DURACION,
    f.HORARIO,
    c.NOMBRE AS CINE
FROM FUNCION f
INNER JOIN CINE c ON f.CINE_ID = c.ID_CINE
ORDER BY 
    f.PELICULA ASC, 
    f.DURACION ASC;

--6.ORDENAR LOS CINES POR CIUDAD Y LUEGO POR NUMERO DE SALAS(UNA SOLA CONSULTA)
SELECT 
    ID_CINE,
    NOMBRE,
    CIUDAD,
    SALAS,
    TIPO
FROM 
    CINE
ORDER BY 
    CIUDAD ASC,
    SALAS DESC;
--7.MOSTRAR EL TOTAL DE DURACION DE PELICULAS PROYECTADAS EN CADA CINE //INNER JOIN
SELECT 
    c.NOMBRE AS CINE,
    SUM(f.DURACION) AS TOTAL_DURACION
FROM 
    CINE c
INNER JOIN 
    FUNCION f ON c.ID_CINE = f.CINE_ID
GROUP BY c.NOMBRE
ORDER BY c.NOMBRE;

--8.MOSTRAR LA FUNCION CON LA PELICULA MAS LARGA DE CADA CINE //INNER JOIN
SELECT 
    c.NOMBRE AS CINE,
    f.PELICULA,
    f.DURACION
FROM 
    CINE c
INNER JOIN 
    FUNCION f ON c.ID_CINE = f.CINE_ID
INNER JOIN (
    SELECT 
        CINE_ID,
        MAX(DURACION) AS MAX_DURACION
    FROM 
        FUNCION
    GROUP BY 
        CINE_ID
) max_f ON f.CINE_ID = max_f.CINE_ID AND f.DURACION = max_f.MAX_DURACION
ORDER BY 
    c.NOMBRE;

--9.MOSTRAR LAS FUNCIONES QUE NO TIENEN CINE ASIGNADO //LEFT JOIN
SELECT 
    f.ID_FUNCION,
    f.PELICULA,
    f.DURACION,
    f.HORARIO,
    f.CINE_ID,
    f.CLASIFICACION
FROM 
    FUNCION f
LEFT JOIN 
    CINE c ON f.CINE_ID = c.ID_CINE
WHERE 
    c.ID_CINE IS NULL;

--10.MOSTRAR LOS CINES QUE NO TIENEN FUNCIONES ASIGNADAS //RIGHT JOIN
    SELECT 
    c.ID_CINE,
    c.NOMBRE,
    c.CIUDAD
FROM 
    CINE c
LEFT JOIN 
    FUNCION f ON c.ID_CINE = f.CINE_ID
WHERE 
    f.ID_FUNCION IS NULL;


--11.MOSTRAR EL DETALLE DEL CINE Y DE LAS FUNCIONES EN UNA SOLA COLUMNA USANDO CONCAT O PIPES //INNER JOIN
--EJEMPLO LA FUNCION AVENGERS EN EL CINE CINEMEX QUE ES TIPO IMAX Y ESTA UBICADO EN LA CIUDAD DE MONTERREY DURA 120 MINUTOS Y EL CLASIFICACION A
SELECT 
    'La función ' || f.PELICULA || ' en el cine ' || c.NOMBRE || 
    ' que es tipo ' || 
        CASE c.TIPO
            WHEN 1 THEN 'TRADICIONAL'
            WHEN 2 THEN 'VIP'
            WHEN 3 THEN 'IMAX'
        END || 
    ' y está ubicada en la ciudad de ' || c.CIUDAD || 
    ' dura ' || f.DURACION || ' minutos y la clasificación es ' ||
        CASE f.CLASIFICACION
            WHEN 1 THEN 'A'
            WHEN 2 THEN 'B'
            WHEN 3 THEN 'C'
            WHEN 4 THEN 'PG13'
            WHEN 5 THEN 'R'
        END AS DETALLE
FROM 
    FUNCION f
INNER JOIN 
    CINE c ON f.CINE_ID = c.ID_CINE;


