--PRACTICA PARA EL USO DE SENTENCIA CASE

--CREAR LA TABLA PRODUCTO

CREATE TABLE PRODUCTO (
ID_PRODUCTO NUMBER,
NOMBRE NVARCHAR2(100),
CATEGORIA NUMBER, --1. ALIMENTO 2.BEBIDA 3.ELECTRODOMESTICO 4.ROPA 5.LIMPIEZA
PRECIO NUMBER,
STOCK NUMBER,
MARCA NVARCHAR2(100),
CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO)
);

INSERT INTO PRODUCTO VALUES(1, 'Arroz Integral 1kg', 1, 45.50, 200, 'La Moderna');
INSERT INTO PRODUCTO VALUES(2, 'Refresco Cola 2L', 2, 28.00, 90, 'Coca-Cola');
INSERT INTO PRODUCTO VALUES(3,'CAMISA MANGA CORTA',4,19.99,75,'MODA JOVEN');
INSERT INTO PRODUCTO VALUES(4,'LICUADORA 3 VELOCIDADES',3,125,50,'ELECTROLUZ');
INSERT INTO PRODUCTO VALUES(5, 'CEREAL ZUCARITAS 500G', 1, 65, 40, 'KELLOGGS');
INSERT INTO PRODUCTO VALUES(6, 'REFRESCO COCA-COLA 2L', 2, 38, 60, 'COCA-COLA');
INSERT INTO PRODUCTO VALUES(7, 'Playera Deportiva', 4, 299.00, 50, 'Nike');
INSERT INTO PRODUCTO VALUES(8, 'Pantalón Casual', 4, 499.00, 40, 'Levi’s');

--ACTIVIDADES
--CONSULTA CASE PARA MOSTRAR LA CATEGORIA

SELECT ID_PRODUCTO, NOMBRE, 
(CASE CATEGORIA
      WHEN 1 THEN 'ALIMENTO'
      WHEN 2 THEN 'BEBIDA'
      WHEN 3 THEN 'ELECTRODOMESTICO'
      WHEN 4 THEN 'ROPA'
      WHEN 5 THEN 'LIMPIEZA'
      ELSE 'SIN CATEGORIA'
      END
      ) AS CATEGORIA , PRECIO, STOCK, MARCA FROM PRODUCTO;
      
--CONSULTA CASE PARA CLASIFICAR EL PRECIO BARATO MEDIO CARO
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA,
(CASE
     WHEN PRECIO >= 100 THEN 'PRECIO CARO ' ||PRECIO|| ' PESOS'
     WHEN PRECIO BETWEEN 50 AND 90 THEN 'PRECIO MEDIO ' ||PRECIO|| ' PESOS'
     WHEN PRECIO <= 50 THEN 'PRECIO BARATO ' ||PRECIO|| ' PESOS'
     ELSE 'PRECIO FUERA DE CATEGORIA'
     END
     ) AS PRECIO, STOCK, MARCA FROM PRODUCTO;

--CONSULTA CON CASE PARA CLASIFICAR EL STOCK SOBRANTE SUFICIENTE ESCASO
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA, PRECIO,
       CASE
            WHEN STOCK >= 200 THEN 'STOCK SOBRANTE ' || STOCK || ' CANTIDAD DE PRODUCTOS'
            WHEN STOCK BETWEEN 51 AND 199 THEN 'STOCK SUFICIENTE ' || STOCK || ' CANTIDAD DE PRODUCTOS'
            WHEN STOCK <= 50 THEN 'STOCK ESCASO ' || STOCK || ' CANTIDAD DE PRODUCTOS'
            ELSE 'STOCK DESCONOCIDO'
       END AS STOCK,
       MARCA
FROM PRODUCTO;

     
     DELETE  FROM PRODUCTOS;
     
     SELECT * FROM PRODUCTO;

