spring.application.name=ApiGateway
server.port=9000

#el api gateway es un componente en la arquitectura de microservicios que actua como un puerto de entrada unico
#basicamente lo que hace es para gestionar todas las solicitudes hacia los microservivios backend y la funcion principal es intermediar, enrutar y
#gestionar el trafico de los clientes y microservicios


#habilitarlo como eureka client
spring.cloud.service-registry.auto-registration.enable=true

#configuracion de los servicios a registrar y gestionar

#Empleado
spring.cloud.gateway.mvc.routes[0].id=Empleado
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8015
spring.cloud.gateway.mvc.routes[0].predicates=Path=/E/**

#Categoria
spring.cloud.gateway.mvc.routes[1].id=Categoria
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8011
spring.cloud.gateway.mvc.routes[1].predicates=Path=/C/**


#Cliente
spring.cloud.gateway.mvc.routes[2].id=Cliente
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8014
spring.cloud.gateway.mvc.routes[2].predicates=Path=/Client/**


#Producto
spring.cloud.gateway.mvc.routes[3].id=Producto
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8010
spring.cloud.gateway.mvc.routes[3].predicates=Path=/P/**



#Proveedor
spring.cloud.gateway.mvc.routes[4].id=Proveedor
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8012
spring.cloud.gateway.mvc.routes[4].predicates=Path=/Proveedor/**


#Ventas
spring.cloud.gateway.mvc.routes[5].id=Ventas
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8013
spring.cloud.gateway.mvc.routes[5].predicates=Path=/V/**























