spring.application.name=ApiGateway

server.port=9000

#el api gateway es un componente en la arquitectura de microservicios que actua como un puerto de entrada unico
#basicamente lo que hace es para gestionar todas las solicitudes hacia los microservivios backend y la funcion principal es intermediar, enrutar y
#gestionar el trafico de los clientes y microservicios


#habilitarlo como eureka client
spring.cloud.service-registry.auto-registration.enable=true

#configuracion de los servicios a registrar y gestionar

#Clientes
spring.cloud.gateway.mvc.routes[0].id=Clientes
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8010
spring.cloud.gateway.mvc.routes[0].predicates=Path=/C/**

#Veterinarias
spring.cloud.gateway.mvc.routes[3].id=Veterinarias
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8011
spring.cloud.gateway.mvc.routes[3].predicates=Path=/V/**

#Mascotas
spring.cloud.gateway.mvc.routes[1].id=Mascotas
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8012
spring.cloud.gateway.mvc.routes[1].predicates=Path=/M/**


#Responsables
spring.cloud.gateway.mvc.routes[2].id=Responsables
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8013
spring.cloud.gateway.mvc.routes[2].predicates=Path=/R/**



