spring.application.name=EurekaServer

#configuracion de el puerto
server.port=8761

#configuracion del host donde se estara ejecutando el servidor eureka
eureka.instance.hostname=localhost

#especificar el url del servidor al que debe conectarse y descubrir otros microservicios
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#indicar que el cliente no debe registarse en el servidor
eureka.client.register-with-eureka=false

#el cliente no debe obtener el registro de los demas servicios de eureka
eureka.client.fetch-registry=false

#ayudar al servidor contra la perdida de demasiadasn instancias en caso de red inestable o problemas temporales de comunicacion
eureka.server.enable-self-preservation=true

#exponer todos los endpoints de administracion
management.endpoints.web.exposure.include=*

#mostrar el detalle completo del estado de la salud de la aplicacion
management.endpoint.health.show-details=always
