-- Microservicio: VETERINARIAS  H2 DATABASE
CREATE TABLE VETERINARIAS (
    ID_VETERINARIA NUMBER(10) PRIMARY KEY,
    NOMBRE         NVARCHAR2(50),
    DIRECCION      NVARCHAR2(100),
    TELEFONO       NUMBER(10)
);

-- Microservicio: CLIENTES  H2 DATABASE
CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER(10) PRIMARY KEY,
    NOMBRE     NVARCHAR2(50),
    DIRECCION  NVARCHAR2(100),
    CONTACTO   NUMBER(10)
);

-- Microservicio: RESPONSABLES  ORACLE
CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE         NVARCHAR2(50),
    CONTACTO       NUMBER(10),
    VETERINARIA_ID NUMBER(10)
);

-- Microservicio: MASCOTAS  ORACLE
CREATE TABLE MASCOTAS (
    ID_MASCOTA      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          NVARCHAR2(15) NOT NULL,
    RAZA            NVARCHAR2(15),
    EDAD            NUMBER(3),
    RAZON_CITA      NVARCHAR2(100),
    CLIENTE_ID      NUMBER(10), 
    RESPONSABLE_ID  NUMBER(10)
);



INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) 
VALUES ('Carlos Pérez', 2223456789, 1);

INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) 
VALUES ('Ana Martínez', 2229876543, 2);

INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) 
VALUES ('Luis Gómez', 2221234567, 1);
COMMIT;


INSERT INTO MASCOTAS (NOMBRE, RAZA, EDAD, RAZON_CITA, CLIENTE_ID, RESPONSABLE_ID)
VALUES ('Firulais', 'Labrador', 3, 'Vacunación', 1, 1);

INSERT INTO MASCOTAS (NOMBRE, RAZA, EDAD, RAZON_CITA, CLIENTE_ID, RESPONSABLE_ID)
VALUES ('Mishi', 'Siames', 2, 'Consulta general', 2, 2);

INSERT INTO MASCOTAS (NOMBRE, RAZA, EDAD, RAZON_CITA, CLIENTE_ID, RESPONSABLE_ID)
VALUES ('Rocky', 'Bulldog', 5, 'Cirugía dental', 3, 1);

INSERT INTO MASCOTAS (NOMBRE, RAZA, EDAD, RAZON_CITA, CLIENTE_ID, RESPONSABLE_ID)
VALUES ('Nina', 'Chihuahua', 1, 'Desparasitación', 4, 3);
COMMIT;

SELECT * FROM MASCOTAS;

SELECT * FROM RESPONSABLES;