-- TABLA CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTEDIGITAL VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDOPATERNO VARCHAR2(50),
    APELLIDOMATERNO VARCHAR2(50),
    GENERO CHAR(1),
    FECHANACIMIENTO DATE,
    CURP VARCHAR2(18)
);

-- TABLA CONTACTO
CREATE TABLE CONTACTO (
    IDCONTACTO VARCHAR2(36) PRIMARY KEY,
    IDCLIENTEDIGITAL VARCHAR2(20),
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(50),
    CONSTRAINT FK_CLIENTE_CONTACTO FOREIGN KEY (IDCLIENTEDIGITAL) REFERENCES CLIENTE(IDCLIENTEDIGITAL)
);

-- Domicilio Cliente
CREATE TABLE DOMICILIO (
    IDDOMICILIO VARCHAR2(36) PRIMARY KEY,
    IDCLIENTEDIGITAL VARCHAR2(20),
    ENTIDADFEDERATIVA VARCHAR2(50),
    MUNICIPIO VARCHAR2(50),
    COLONIA VARCHAR2(50),
    CALLE VARCHAR2(50),
    NUMEROINTERIOR VARCHAR2(10),
    NUMEROEXTERIOR VARCHAR2(10),
    CODIGOPOSTAL VARCHAR2(10),
    PAIS VARCHAR2(50),
    CONSTRAINT FK_CLIENTE_DOMICILIO FOREIGN KEY (IDCLIENTEDIGITAL) REFERENCES CLIENTE(IDCLIENTEDIGITAL)
);

-- DOCUMENTACION
CREATE TABLE DOCUMENTACION (
    IDDOCUMENTACION VARCHAR2(36) PRIMARY KEY,
    IDCLIENTEDIGITAL VARCHAR2(20),
    TIPOIDENTIFICACION VARCHAR2(20),
    NUMEROIDENTIFICACION VARCHAR2(50),
    CONSTRAINT FK_CLIENTE_DOCUMENTACION FOREIGN KEY (IDCLIENTEDIGITAL) REFERENCES CLIENTE(IDCLIENTEDIGITAL)
);

-- BENEFICIARIO
CREATE TABLE BENEFICIARIO (
    IDBENEFICIARIO VARCHAR2(36) PRIMARY KEY,
    IDCLIENTEDIGITAL VARCHAR2(20),
    NOMBRE VARCHAR2(50),
    APELLIDOPATERNO VARCHAR2(50),
    APELLIDOMATERNO VARCHAR2(50),
    FECHANACIMIENTO DATE,
    CONSTRAINT FK_CLIENTE_BENEFICIARIO FOREIGN KEY (IDCLIENTEDIGITAL) REFERENCES CLIENTE(IDCLIENTEDIGITAL)
);

-- DOMICILIO BENEFICIARIO
CREATE TABLE DOMICILIOBENEFICIARIO (
    IDDOMICILIO VARCHAR2(36) PRIMARY KEY,
    IDBENEFICIARIO VARCHAR2(36),
    ENTIDADFEDERATIVA VARCHAR2(50),
    MUNICIPIO VARCHAR2(50),
    COLONIA VARCHAR2(50),
    CALLE VARCHAR2(50),
    NUMEROINTERIOR VARCHAR2(10),
    NUMEROEXTERIOR VARCHAR2(10),
    CODIGOPOSTAL VARCHAR2(10),
    PAIS VARCHAR2(50),
    CONSTRAINT FK_BENEFICIARIO_DOMICILIO FOREIGN KEY (IDBENEFICIARIO) REFERENCES BENEFICIARIO(IDBENEFICIARIO)
);

-- PRODUCTO
CREATE TABLE PRODUCTO1 (
    IDPRODUCTO VARCHAR2(20) PRIMARY KEY,
    NOMBREPRODUCTO VARCHAR2(50)
);

-- CONTRATO
CREATE TABLE CONTRATO (
    IDCONTRATO VARCHAR2(20) PRIMARY KEY,
    IDCLIENTEDIGITAL VARCHAR2(20),
    IDPRODUCTO VARCHAR2(20),
    FECHAEXPIRACION DATE,
    CONSTRAINT FK_CLIENTE_CONTRATO FOREIGN KEY (IDCLIENTEDIGITAL) REFERENCES CLIENTE(IDCLIENTEDIGITAL),
    CONSTRAINT FK_PRODUCTO_CONTRATO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO1(IDPRODUCTO)
);

SELECT * FROM CLIENTE;

delete from CONTRATO ;     
delete from PRODUCTO1 ;
delete from DOMICILIOBENEFICIARIO ;
delete from BENEFICIARIO ;
delete from DOCUMENTACION ;
delete from DOMICILIO ;
delete from CONTACTO ;
delete from CLIENTE ;
commit;
