-- CREACION DE TABLA CARROS
CREATE TABLE CARROS (
    ID_CARRO     NUMBER,
    MARCA        NVARCHAR2(100),
    MODELO       NVARCHAR2(100),
    ANIO         NUMBER(4),
    COLOR        NVARCHAR2(50),
    MOTOR        NVARCHAR2(100),
    TRANSMISION  NVARCHAR2(50),
    PRECIO       NUMBER,
    CONSTRAINT CARRO_PK PRIMARY KEY (ID_CARRO)
);

--BEFORE = ANTES
--CREAR UNA SEQUENCE
CREATE SEQUENCE SEQ_CARRO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

--TRIGGER BEFORE PARA CREAR EL ID_COMPU DE FORMA AUTOMATICA CON LA SECUENCIA
CREATE OR REPLACE TRIGGER TR_CARRO_ID
BEFORE INSERT ON CARROS --ACTUARA ANTES DE QUE OCURRA UNA INSERSION EN LA TABLA COMPUTADORA
FOR EACH ROW
BEGIN
-- SI NO SE PROPORCIONA UN ID LO ASIGNA CON LA SECUENCIA
IF :NEW.ID_CARRO IS NULL THEN
   :NEW.ID_CARRO := SEQ_CARRO.NEXTVAL;
   END IF ;
   END;
   /
   
   
   -- INSERTS PARA TABLA CARROS
INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Toyota', 'Corolla', 2022, 'Blanco', '1.8L', 'Automática', 350000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Honda', 'Civic', 2021, 'Rojo', '2.0L', 'Manual', 320000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Ford', 'Mustang', 2023, 'Negro', '5.0L V8', 'Automática', 950000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Chevrolet', 'Aveo', 2020, 'Azul', '1.5L', 'Manual', 210000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Nissan', 'Versa', 2022, 'Gris', '1.6L', 'Automática', 250000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Mazda', 'CX-5', 2023, 'Blanco', '2.5L', 'Automática', 480000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Volkswagen', 'Jetta', 2021, 'Plateado', '1.4L Turbo', 'Manual', 310000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Hyundai', 'Tucson', 2022, 'Rojo', '2.0L', 'Automática', 420000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('Kia', 'Rio', 2020, 'Negro', '1.6L', 'Manual', 230000);

INSERT INTO CARROS (MARCA, MODELO, ANIO, COLOR, MOTOR, TRANSMISION, PRECIO)
VALUES ('BMW', 'Serie 3', 2023, 'Azul Marino', '2.0L Turbo', 'Automática', 820000);

COMMIT;

SELECT * FROM CARROS;
