--CREACION DE TABLA PARA MI PRIMER SERVIVIO WEB
CREATE TABLE COMPUTADORA(
ID_COMPU NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
RAM NUMBER,
CAPACIDAD NVARCHAR2(100),
COLOR NVARCHAR2(100),
PRECIO NUMBER,
CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

--BEFORE = ANTES
--CREAR UNA SEQUENCE
CREATE SEQUENCE SEQ_COMPU
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

--TRIGGER BEFORE PARA CREAR EL ID_COMPU DE FORMA AUTOMATICA CON LA SECUENCIA
CREATE OR REPLACE TRIGGER TR_COMPU_ID
BEFORE INSERT ON COMPUTADORA --ACTUARA ANTES DE QUE OCURRA UNA INSERSION EN LA TABLA COMPUTADORA
FOR EACH ROW
BEGIN
-- SI NO SE PROPORCIONA UN ID LO ASIGNA CON LA SECUENCIA
IF  :NEW.ID_COMPU IS NULL THEN
   :NEW.ID_COMPU := SEQ_COMPU.NEXTVAL;
   END IF ;
   END;
   /
   
INSERT INTO COMPUTADORA (MARCA,MODELO,RAM,CAPACIDAD,COLOR,PRECIO) VALUES ('DELL','Inspiron 15',16,'512GB SSD','Negro',15000);

SELECT * FROM COMPUTADORA;
   
   DELETE FROM COMPUTADORA;
   COMMIT;
   