CREATE TABLE AUTOR(
ID_AUTOR NUMBER,
NOMBRE NVARCHAR2(100),
NACIONALIDAD NVARCHAR2(50),
FECHA_NACIMIENTO DATE,
CONSTRAINT AUTOR_PK PRIMARY KEY(ID_AUTOR)
);

CREATE TABLE LIBROS(
ID_LIBRO NUMBER,
TITULO NVARCHAR2(150),
GENERO NVARCHAR2(50),
ANIO_PUBLICACION NUMBER,
PRECIO NUMBER,
AUTOR_ID NUMBER,
CONSTRAINT LIBRO_PK3 PRIMARY KEY(ID_LIBRO),
CONSTRAINT AUTOR_FK3 FOREIGN KEY(AUTOR_ID) REFERENCES AUTOR(ID_AUTOR)
);

INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO)
VALUES (1, 'Gabriel García Márquez', 'Colombiana', TO_DATE('1927-03-06', 'YYYY-MM-DD'));

INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO)
VALUES (2, 'Isabel Allende', 'Chilena', TO_DATE('1942-08-02', 'YYYY-MM-DD'));

INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO)
VALUES (3, 'Mario Vargas Llosa', 'Peruana', TO_DATE('1936-03-28', 'YYYY-MM-DD'));
COMMIT;


INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (101, 'Cien años de soledad', 'Realismo mágico', 1967, 350, 1);

INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (102, 'El amor en los tiempos del cólera', 'Romance', 1985, 280, 1);

INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (103, 'La casa de los espíritus', 'Realismo mágico', 1982, 300, 2);

INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (104, 'Paula', 'Autobiografía', 1994, 250, 2);

INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (105, 'La ciudad y los perros', 'Novela', 1963, 320, 3);

INSERT INTO LIBROS (ID_LIBRO, TITULO, GENERO, ANIO_PUBLICACION, PRECIO, AUTOR_ID)
VALUES (106, 'Conversación en La Catedral', 'Novela', 1969, 330, 3);
COMMIT;

SELECT * FROM LIBROS;