spring.application.name=UsuariosRoles

#puerto
server.port=8002

#configuracion de oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=JORGECONTRERAS
spring.datasource.password=280400
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.formary-sql=true

logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
