spring.application.name=PadreHijo

#puerto
server.port=8001

#configuracion de oracle
spring.datasource.url=jdbc:oracle:thin:@oracle-db:1521/XE
spring.datasource.username=SYSTEM
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.formary-sql=true

logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
